### ISSUE TITLE
BE_Version provides no result when Get(ApplicationVersion) = Web Publishing Engine

### ISSUE THREAD

**Issue by petrowsky** [GoyaPtyLtd/BaseElements-Plugin#101]
Using BaseElements 3.0.0 on an FMPS13 or 14 returns "?" when calling BE_Version.

I'm using a version checking script to make sure the plug is not deactivated on a server update (which happens)

Both calling BE_Version direct and using Evaluate as a wrapper results in "?" when the environment running the script is WPE. Here's my script.

```
Set Variable [$version; Value:Evaluate ( "BE_Version" )]
Set Variable [$expected; Value:3]
Set Variable [$minRequired; Value:Int ( Substitute ( $version ; "," ; "." ) ) ≥ $expected // swapping comma for periods supports international]
# Debugging
Exit Script [Result: List( 	"BE Direct = " & BE_Version; 	"Version = " & $version; 	"Min Version = " & $minRequired; 	$version = "?" or not $minRequired )]
#
Perform Script [“Pushover ( message )”; Parameter: # ( "message" ; Get(ApplicationVersion) )]
If [$version = "?" or not $minRequired]
	Set Variable [$message; Value:"Required Base Elements plugin not installed on " & Get ( HostName ) & " (" & Get ( HostIPAddress ) & ")"]
	Perform Script [“Pushover ( message )”; Parameter: # ( "message" ; $message )]
	Halt Script
End If
```

When setting the script up and testing via PSOS it works out fine, when running it via WPE it provides no result. Is there something I'm missing?

**Comment by petrowsky** [comment]
Found a response from @nickorr on #52 will try putting the plugin in a location for WPE.

**Comment by dansmith65** [comment]
FYI: if you use http://www.modularfilemaker.org/module/pluginmanager/, it will install  the plugin for you in the appropriate location.

**Comment by petrowsky** [comment]
@dansmith65 I have my own plugin installer file which will install into the location for the DB server using  the built-in functions within FMP.

But, are you saying you've added functionality to install into /Web Publishing/publishing-engine/cwpc/Plugins? Which is where a second copy of the plugin needs to be in order to get WPE scripts to be able to use the plugin.

**Comment by petrowsky** [comment]
This is essentially a closed issue as getting BaseElements to run on Win Server under WPE requires you to install the plugin in an additional location.

/Database Server/Extensions (for the fmapp running PSOS)
and
/Web Publishing/publishing-engine/cwpc/Plugins (for fmphp running under WPE)

**Comment by dansmith65** [comment]
> I have my own plugin installer file which will install into the location for the DB server using the built-in functions within FMP.
> But, are you saying you've added functionality to install into /Web Publishing/publishing-engine/cwpc/Plugins? Which is where a second copy of the plugin needs to be in order to get WPE scripts to be able to use the plugin.

Yes, I have. If you call the Plugin Checker module sometime before you use a plugin, it will install the plugin in the appropriate place for the current application.

IIRC, the trick was to use PSoS to call a separate script to determine the Server's OS, so the correct plugin could be installed.
