### ISSUE TITLE
BE_SMTP_Sent() - full name not supported in from parameter

### ISSUE THREAD

**Issue by nilswald** [GoyaPtyLtd/BaseElements-Plugin#103]
Hi!

First of all, thanks for the new release - your plugin is just awesome!

Although setting the reply-to with `John Doe <john@doe.net>` is supported, doing so with from (cc, bcc) raises an error *55 - CURLE_SEND_ERROR: Failed sending network data.*

Or is there an alternative syntax?

Greetings!

Nils

**Comment by nickorr** [comment]
Nils,

Can you send me details?  Copy the function calls, and then run the BE_Curl_Trace after doing the send, and send me the contents of that.

Cheers,
Nick

**Comment by nilswald** [comment]
Hi Nick,

it seems, that curl/BE wraps the 'from' parameter in <>:

0000: MAIL FROM:<FromName <from@ca.waldherr.de>> SIZE=37562
<= Recv header, 0x4c bytes (0x4c)
0000: 501 <FromName <from@ca.waldherr.de>>: "@" or "." expected after 
0x40: "FromName"
== Info: MAIL failed: 501

if I use the name only with the reply-to it looks like this:

0x67: To: to@ca.waldherr.de
0x7e: From: from@ca.waldherr.de
0x99: Subject: 
0xa4: Reply-To: ReplyName <reply@ca.waldherr.de>
0xd0: CC: 
0xd6: BCC: 


Kind regards,

Nils

**Comment by nickorr** [comment]
Nils,

I think this is fixed in the latest beta, I've sent you a copy offlist.

Thanks,
Nick
