### ISSUE TITLE
BE_SMTP_Send() - inline attachments?

### ISSUE THREAD

**Issue by nilswald** [GoyaPtyLtd/BaseElements-Plugin#104]
Hi,

are inline attachments already supported or planned? It could be implemented transparently by adding something to the path, like:

```
inline:/Users/nils/Desktop/myInlineAttachment.jpg
```

this would result in the slightly different header for that part:

```
Content-Disposition: inline;
	filename= myInlineAttachment.jpg
Content-Id: <myInlineAttachment.jpg@be.generated>
```

adding it to your html woold be as easy as this:

```
<img src=cid:myInlineAttachment.jpg@be.generated>
```

What do you think?

Best regards,

Nils

**Comment by nickorr** [comment]
Nils,

It’s not on the todo list at the moment.  If you’d like to see it, consider sponsoring, this would be the sort of request we could take.

Cheers,
Nick
