### ISSUE TITLE
Update functions documentation

### ISSUE THREAD

**Issue by rwu2359** [GoyaPtyLtd/BaseElements-Plugin#105]
please.. its quite out of date

**Comment by nickorr** [comment]
John,

Updated docs are now here : https://baseelementsplugin.zendesk.com/hc/en-us <https://baseelementsplugin.zendesk.com/hc/en-us>

Cheers,
Nick

**Comment by rwu2359** [comment]
Thank you Nick...
Think I had stumbled into them in the meantime

Great plug-in, just put it onto a clients server to do file management and
is a solid as anything I could wish for.

john
