### ISSUE TITLE
BE_ExecuteSystemCommand is not unicode compatible

### ISSUE THREAD

**Issue by user19752** [GoyaPtyLtd/BaseElements-Plugin#106]
BE_ExecuteSystemCommand ( "cmd /a /c echo 123" ) get 123
but
BE_ExecuteSystemCommand ( "cmd /u /c echo 123" ) get 1

I guess that command string is converted with utf8toutf16, but the result is not.

**Comment by nickorr** [comment]
The plugin expects the response to be utf8, and anything else will attempt to be treated as such.  So the /u option forces UCS-2 which isn't supported.

Cheers,
Nick

**Comment by user19752** [comment]
So, the function is useless.

Saying in document
On Windows you need to prefix your command with "cmd.exe /c". For example "cmd.exe /c dir" will list the directory contents
But it runs same as using /a option, response is not utf8. Only ASCII environment it can be useful. On my Japanese Windows result is broken or FM hangs some time for example  "cmd.exe /c dir" without using timeout parameter.

**Comment by nickorr** [comment]
It's not useless, it just doesn't work for you.

If you'd like it behave differently please consider sponsoring and requesting this feature : http://www.goya.com.au/baseelements/plugin/sponsors

Github issues are for support with compiling the plugin or development ( of the plugin ) issues only.

Cheers,
Nick

**Comment by user19752** [comment]
Thanks, of course it may be useful for many users.

I am not considering sponsoring and feature request, I wanted to do bug report. Is there any place?

The function may be working some environment, but it is only something accidentally that utf8 is compatible for ASCII.
If saying "prefix cmd.exe", the response from internal commands are system native encoding or USC-2.

OTOH, running external commands there is no need to prefix, like
BE_ExecuteSystemCommand ( "netstat -an -p tcp" )
and response will be any encoding the program use.

I tried to build it myself, but it is difficult to me without having no C++ experience, especially getting many depending libraries.
