### ISSUE TITLE
BE_Encrypt_AES and BE_Decrypt_AES won't work on iOS

### ISSUE THREAD

**Issue by stevenzhenyuli** [GoyaPtyLtd/BaseElements-Plugin#107]
I am attempting to use AES to encode a password field, but the iOS FileMaker GO 14 client won't perform these two functions properly. 

Testing the two functions with a custom dialog showed that the output of both functions were "?" on iOS, while the same script on FileMaker Pro 14 generated correct encrypted or decrypted text. 

Testing condition: GO 14 client connected to a database through LAN sharing.

**Comment by nickorr** [comment]
stevenzhenyuli,

Plugins don’t run on iOS, so this won’t work.

Cheers,
Nick
