### ISSUE TITLE
BE_ReadTextFromFile choking on curly quotes

### ISSUE THREAD

**Issue by petrowsky** [GoyaPtyLtd/BaseElements-Plugin#108]
I hit an issue today where I had data being exported via the standard Export step. I tried both Macintosh and Windows ANSI character sets. I then tried to read it in with BE_ReadTextFromFile. The data included single curly quotes.

BE_ReadTextFromFile was failing with an error 92 when the content included curly quotes (U+2019).

Is this a known issue?

**Comment by nickorr** [comment]
The simplest way would be to use the default, which is utf8 which works for most things.  Do you need it to be a certain character set?

Cheers,
Nick

**Comment by petrowsky** [comment]
Unfortunately for my situation I'm using a Merge export. It looks like UTF-8 and UTF-16 are only available on Tab and CSV. If you need the field headers, like I do, then Merge is your only option and they don't provide UTF encoding. :(

![screen shot 2015-08-27 at 16 41 58](https://cloud.githubusercontent.com/assets/96553/9535918/3fc1bb34-4cdb-11e5-8a2f-4139a0f68100.png)

I'm guessing I might be the first person to hit this issue? I can address it by converting smart quotes into standard, but given that a FileMaker file could have smart quotes turned on in prefs and a user could choose the Merge export format, they would hit this same issue unless you were able to detect the encoding and account for non UTF. :(

**Comment by petrowsky** [comment]
If I'm the only one then I'll just detect and convert smart quotes. It seems like it should be an FMI issue to fix. I don't know how much extra effort it would be worth to fix.

**Comment by nickorr** [comment]
Matt,

any chance you can send me a sample of this?  You’re exporting from FileMaker and then trying to read in with the plugin, is that right?

Cheers,
Nick

**Comment by marketconnections** [comment]
I'm also having trouble. Version 3.0 supported reading UCS-2 LE BOM encoding no problem (don't ask).  
Version 3.1 returns "?" and BE_LastError returns 42.

**Comment by nickorr** [comment]
Can you post some sample files, so I can test?

Thanks,
Nick

**Comment by cressije** [comment]
Hello nick, I have the same problem with version 3.1. "?" and errors 42
Do you find the problem, do you have a resolution ?? 
I need this fonctionnality, can I find the older version of the plugin, maybe 3.0 or 2.2 ?? Compatible with FMServer14 ??
Merci d'avance !

**Comment by nickorr** [comment]
I can read in a text file with quotes just fine in utf8, can you send me a sample text file and the function calls you're using?  send direct to nick@goya.com.au

Thanks,
Nick
