### ISSUE TITLE
JSON encoding not intuitive

### ISSUE THREAD

**Issue by rwu2359** [GoyaPtyLtd/BaseElements-Plugin#109]
BE_JSON_Encode ( "firstName" ; BE_JSON_Encode ( "one" ; "two" ) & "," & BE_JSON_Encode ( "three" ; "four" ) )
produces
"firstName":"\"one\":\"two\",\"three\":\"four\""
not
"firstName":{"one":"two","three":"four"} which is valid JSON
which means you can pretty print it without substitutions first

**Comment by dansmith65** [comment]
How would the outer `BE_JSON_Encode` function know if the value was an object vs a string?

**Comment by nickorr** [comment]
John,

Like Dan said, you can't pass the result of an encode as a parameter as it then thinks it's text ( not JSON ) and encodes it.  So you do it in sections :

BE_JSON_Encode ( "firstName" ) & "{" & 
BE_JSON_Encode ( "one" ; "two" ) & "," & 
BE_JSON_Encode ( "three" ; "four" ) & "}"

Cheers,
Nick
