### ISSUE TITLE
ExecuteSystemCommand for installed Windows libraries

### ISSUE THREAD

**Issue by imarcw** [GoyaPtyLtd/BaseElements-Plugin#111]
Trying to access pdftk within FileMaker using BE_ExecuteSystemCommand on Windows. When I first started using these installed libraries on the Mac, I found that I needed to specify the path to the library ("opt/local/bin/pdftk COMMAND") when calling them with the plugin, whereas in Terminal I could just enter "pdftk COMMAND". So I'm not sure what the equivalent syntax is for Windows. 

(I'm pretty sure pdftk Server, which is what they call their command-line app, is installed at Program Files/pdftk/, which makes it more complicated because a) there's a space in the path, and b)Windows uses backslashes for file path delimiters, which also means "escape the next character" in FileMaker calculations.)

**Comment by nickorr** [comment]
imarcw,

The shell commands from the plugin run in the SH shell, not the BASH shell default, so you won't have the same defaults for paths etc that you have from Terminal.  For the plugin ( Mac or Windows ) always use full paths.

For backslashes in FileMaker, they need to be escaped as \\ and quotes as \", then they should come through to the plugin just fine.

The git issues queue is really for technical issues around compiling the plugin.  For plugin support consider sponsoring : http://www.goya.com.au/baseelements/plugin/sponsors

Cheers,
Nick
