### ISSUE TITLE
BE_HTTP_POST and file upload path with ampersand

### ISSUE THREAD

**Issue by tohvanah** [GoyaPtyLtd/BaseElements-Plugin#112]
Using the @file parameter has worked fine on OS X for me for awhile now. However I'm encountering it failing with an ampersand in the path (a folder). I can't find anyway to encode the ampersand and have it not fail. 

Please advise, thank you!

**Comment by nickorr** [comment]
Have you tried GetAsURLEncoded?

Cheers,
Nick

**Comment by tohvanah** [comment]
Yes, when I use GetAsURLEncoded on the parameters string (or just the file path) it fails, with or without an ampersand in the path.

I also tried just using "%26" in place of the ampersand , and escaping it like "\&", both failed.

**Comment by nickorr** [comment]
Any chance you can remove the & from the path??  Copy it to a temp folder?

**Comment by tohvanah** [comment]
For this particular purpose on this day, yes. But I can't tell my clients, don't use an ampersand (and maybe other characters?!) in your folders and documents. If the OS supports them, it seems best practice to support them as well. I recognize that ampersands have a special purpose in POST/query strings, but I expected a way to encode/escape them.

If you/the plugin presents no solutions, I guess I'll have to test for ampersands and any other characters that may present themselves, and copy to temp as you suggest. Thanks.
