### ISSUE TITLE
BE_UNGZIP doesn't seem to work

### ISSUE THREAD

**Issue by kearsdogg** [GoyaPtyLtd/BaseElements-Plugin#113]
I have a container field with a gz file.  i can export it manually and extract the document just fine.  when i try to program that using be_ungzip, the resulting file is the original gzip file.  I've tried quite a few ways to achieve this.

1. set field, container = BE_unGzip( container; "label.pdf")
2. set variable, $x = be_unGzip (container; "label.pdf" )
     set field, container = $x
3. exportfieldcontents ( container ; temporarypath/label.gz )
    set field container = BE_unzip (temporarypath/label.gz; "label.pdf" ) 
4. set field container = BE_UnGzip (container)  - the resulted in "?"

Each results in my container having the "label.pdf" file, but when I export it, adobe won't open it. if i change it back to .gz, it opens to show the zipped content.  I"m not really sure if I'm doing something wrong or if the function is broken. 

[label.pdf](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/71169/label.pdf)

I'm using the 32 bit plugin

**Comment by nickorr** [comment]
kearsdogg,

Can you put together a sample file to show me what you're doing.

Thanks,
Nick

**Comment by kearsdogg** [comment]
If you have it working, may be more helpful to check out your sample file.  Anytime I run the function, it results with the original file.  I can export it and unzip with successfully with 7zip.  I’ve tried on FM 13 v9 and FM 14v4 (64-bit).

Scott Kearsley

Headsets.com, Inc

**Comment by nickorr** [comment]
Scott,

Our test cases are here : https://github.com/GoyaPtyLtd/BaseElements-Plugin/blob/master/Project/Extras/BaseElements%20Plugin%20Tests.fmp12 ( click the view raw button to download a copy ).

There’s a bunch of gzip examples there and they passed the test last time we ran them :)

Cheers,
Nick

**Comment by kearsdogg** [comment]
The test file you're referencing doesn't have a gzip/ungzip sample.  There are plenty of zip/unzip examples.  Am I missing something?
![image](https://cloud.githubusercontent.com/assets/16417646/13181349/8de864da-d6e1-11e5-8832-1da008237ddf.png)

**Comment by nickorr** [comment]
The Gzip functions have been renamed to compress container functions.

Cheers,
Nick

**Comment by kearsdogg** [comment]
Thanks.  I was 1 version behind.  So this function isn’t meant to take a gzip file stored in a container and unzip the contents?  When I try to do that, I get a resulting file identical to the gzip file.

Maybe I’m trying to use it with the wrong intentions.  Now that it’s been renamed, I’m thinking that’s the case.


Scott Kearsley

Headsets.com, Inc
Technology & Support
Database Administrator
1-415-351-5837

Customer Service: 1-800-HEADSETS (1-800-432-3738)
Fax:  800-457-0467
E-mail: ScottK@headsets.com<mailto:ScottK@headsets.com>

**Comment by nickorr** [comment]
Yes, it was that the initial name led people astray as to it’s function.  There will be a new gzip function for unzipping files in a future release.

Cheers,
Nick

**Comment by kearsdogg** [comment]
Ok thanks Nicholas.  I’ll be on the lookout for the future release.

Scott Kearsley

Headsets.com, Inc
Technology & Support
Database Administrator
1-415-351-5837

Customer Service: 1-800-HEADSETS (1-800-432-3738)
Fax:  800-457-0467
E-mail: ScottK@headsets.com<mailto:ScottK@headsets.com>
