### ISSUE TITLE
Trying to push data from FM12 to Jira

### ISSUE THREAD

**Issue by laurabowyer** [GoyaPtyLtd/BaseElements-Plugin#114]
Hello:

I am trying to script to push new tickets from FileMaker 12 to Jira and I followed a thread on the FM talk list, but it doesn't appear to be working. Although I get a result of 0 and when I check the HTTP Response code it is 302. What does that mean?
[Jira Testing.pdf](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/95129/Jira.Testing.pdf)

**Comment by nickorr** [comment]
Laura,

302 is a redirect : https://en.wikipedia.org/wiki/HTTP_302 <https://en.wikipedia.org/wiki/HTTP_302>

So in the content of the HTTP headers that you get after the response, there will be a new url that you need to go to.  Most likely something in your request is not set right.

Cheers,
Nick

**Comment by laurabowyer** [comment]
Thanks Nick!

The response headers didn't have a new address but I suspect our Jira URL might need a port. I'll try that. 

Thanks!

Laura Bowyer
~~~~~~~~~~~~~~~~~~
Sent from my iPhone- please excuse any typos!

> On Jan 18, 2016, at 5:11 PM, Nicholas Orr <notifications@github.com> wrote:
> 
> Laura,
> 
> 302 is a redirect : https://en.wikipedia.org/wiki/HTTP_302 <https://en.wikipedia.org/wiki/HTTP_302>
> 
> So in the content of the HTTP headers that you get after the response, there will be a new url that you need to go to. Most likely something in your request is not set right.
> 
> Cheers,
> Nick
> 
> > On 19 Jan 2016, at 10:33 AM, laurabowyer <notifications@github.com> wrote:
> > 
> > Hello:
> > 
> > I am trying to script to push new tickets from FileMaker 12 to Jira and I followed a thread on the FM talk list, but it doesn't appear to be working Although I get a result of 0 and when I check the HTTP Response code it is 302 What does that mean?
> > Jira Testingpdf <https://githubcom/GoyaPtyLtd/BaseElements-Plugin/files/95129/JiraTestingpdf>
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/GoyaPtyLtd/BaseElements-Plugin/issues/114>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub.
>

**Comment by laurabowyer** [comment]
Hi Nick:

Here is the response code I get - there is no new URL?

HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Location: https://jira.wizards.com/secure/
Transfer-Encoding: chunked
Date: Tue, 19 Jan 2016 17:38:53 GMT

Thanks!
Laura

**Comment by nickorr** [comment]
Yes, this one :

> Location: https://jira.wizards.com/secure/

An API shouldn’t redirect though, unless there’s an auth issue.  So find out what is at that url first.

Cheers,
Nick

**Comment by laurabowyer** [comment]
Got it. Thanks!

Laura Bowyer
~~~~~~~~~~~~~~~~~~
Sent from my iPhone- please excuse any typos!

> On Jan 19, 2016, at 4:08 PM, Nicholas Orr <notifications@github.com> wrote:
> 
> Yes, this one :
> 
> > Location: https://jira.wizards.com/secure/
> 
> An API shouldn’t redirect though, unless there’s an auth issue. So find out what is at that url first.
> 
> Cheers,
> Nick
> 
> 
> > On 20 Jan 2016, at 4:41 AM, laurabowyer <notifications@github.com> wrote:
> > 
> > Hi Nick:
> > 
> > Here is the response code I get - there is no new URL?
> > 
> > HTTP/1.1 302 Found
> > Server: Apache-Coyote/1.1
> > Location: https://jira.wizards.com/secure/
> > Transfer-Encoding: chunked
> > Date: Tue, 19 Jan 2016 17:38:53 GMT
> > 
> > Thanks!
> > Laura
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> 
> —
> Reply to this email directly or view it on GitHub.
>
