### ISSUE TITLE
BE_Zip

### ISSUE THREAD

**Issue by thomann061** [GoyaPtyLtd/BaseElements-Plugin#116]
I am having problems zipping a file that was exported to a windows temporary folder and then using BE_Zip on that.

Can BE_Zip be used on external files or only ones within a container field?

I did not see any tests on external files.

Thanks,
Jacob

**Comment by nickorr** [comment]
It works on external files only.  If you’re having issues, post the details and the error codes, or we can’t help you much…

Cheers,
Nick

**Comment by thomann061** [comment]
![image](https://cloud.githubusercontent.com/assets/9962854/15046673/3ea96056-129e-11e6-93f2-e8e34bb01ace.png)

This script exports the file to my desktop, but does not zip the file.  It gives a ? as the return.

**Comment by nilswald** [comment]
Hi Jacob, 

did you read the [Notes about File Paths](https://baseelementsplugin.zendesk.com/hc/en-us/articles/205350417-Notes-about-File-Paths)?

Nils

**Comment by thomann061** [comment]
I did now.  I thought I am using an operating system path?

**Comment by thomann061** [comment]
It works when I use BE_SelectFile.  But is there a function that selects the file without the prompt?

**Comment by thomann061** [comment]
Wow.  I finally figured it out.  I just had to remove the first slash that Get(DesktopPath) was generating.

Doesn't work -> /C:/
Works -> C:/
