### ISSUE TITLE
http cookie control

### ISSUE THREAD

**Issue by nilswald** [GoyaPtyLtd/BaseElements-Plugin#117]
Hi,

is there any documentation on how http cookies are handled? Are cookies stored and sent transparently? Can this be controlled by BE_Curl_Set_Option( "CURLOPT_COOKIESESSION"; "" ) in order to keep cookies from being sent? In a current project I get 401 errors and I assume these are caused by an outdated session cookie. I would like to force the server to send new cookies (set-cookie).

Nils

**Comment by nickorr** [comment]
Nils,

We don't have anything specific and you're the first person I've heard who has asked about it.  In theory it's entirely possible with the Set Option function, but the actual details are not something I'm familiar with.  I'd suggest starting here :

https://curl.haxx.se/docs/http-cookies.html

and 

http://stackoverflow.com/questions/15995919/curl-how-to-send-cookies-via-command-line

Let me know what you try and what works ( or doesn't ).

Cheers,
Nick
