### ISSUE TITLE
BE_SetClipboardText truncates last character on Windows

### ISSUE THREAD

**Issue by dansmith65** [GoyaPtyLtd/BaseElements-Plugin#118]
This FileMaker expression should return true:

```
BE_SetClipboardText ( "abc" ; "CF_TEXT" )
& ¶
& BE_ClipboardText ( "CF_TEXT" )
=
"1¶abc"
// actual result is "1¶ab"
```

NOTE: I only tested with CF_TEXT format, not sure if this issue applies to other formats.

It looks like the windows clipboard functions were re-written in version 2.1, where this issue first arose. The last version I found with this function working as expected was version 2.0.1. Here's a link to a comparison view of those versions: https://github.com/GoyaPtyLtd/BaseElements-Plugin/compare/2.0.1...2.1

**Comment by nickorr** [comment]
Dan,

CF_TEXT is a standard text type that has special requirements.  From here : https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168(v=vs.85).aspx

Text format. Each line ends with a carriage return/linefeed (CR-LF) combination. A null character signals the end of the data. Use this format for ANSI text.

So I guess it's assuming an EOL character and stripping that out, or having an issue with it not being there.

Cheers,
Nick
