### ISSUE TITLE
Error 0 when installing plugin from FileMaker Pro Advanced on Windows

### ISSUE THREAD

**Issue by ibrahim-bittar** [GoyaPtyLtd/BaseElements-Plugin#119]
Hi Nick

I have the x64 version of BaseElements in a container and when I try to install it via script I get an error of type 0. If I run exactly the same script in FMPA14 it works as expected.

I tried with BE 3.1 and 3.2, same result.

How can I send you more information?

**Comment by nickorr** [comment]
Ibrahim,

Error 0 is success...

Cheers,
Nick
