### ISSUE TITLE
BE_SMTP_Send() -- fails with multiple CC or BCC addresses

### ISSUE THREAD

**Issue by hschlossberg** [GoyaPtyLtd/BaseElements-Plugin#121]
I can add as many TO recipients as I want,  but if I try those same multiple recipients as either CC or BCC, then the email fails with error 55 (CURLE_SEND_ERROR).  A single cc/bcc or no cc/bcc does work correctly.

**Comment by nickorr** [comment]
Howard,

Make sure you've got the latest version, and make sure you're following the formats from here : https://baseelementsplugin.zendesk.com/hc/en-us/articles/204528277-BE-SMTP-Send

If it still fails, send me a transcript.

Cheers,
Nick

**Comment by hschlossberg** [comment]
I can see from the transcript that the second CC address has a space before it, whereas it doesn't in what I send the plugin.

In the function call, the cc parameter is set as:
List( "test123@mydomain.com"; "test456@mydomain.com" )

The pertinent section of the transcript:

=> Send header, 0x23 bytes (0x23)
0000: RCPT TO:<test@mydomain.com>
<= Recv SSL data, 0x5 bytes (0x5)
0000: ....A
<= Recv header, 0x29 bytes (0x29)
0000: 250 2.1.5 OK v126sm849160pfb.60 - gsmtp
=> Send SSL data, 0x5 bytes (0x5)
0000: ....>
=> Send header, 0x26 bytes (0x26)
0000: RCPT TO:<test123@mydomain.com>
<= Recv SSL data, 0x5 bytes (0x5)
0000: ....A
<= Recv header, 0x29 bytes (0x29)
0000: 250 2.1.5 OK v126sm849160pfb.60 - gsmtp
=> Send SSL data, 0x5 bytes (0x5)
0000: ....?
=> Send header, 0x27 bytes (0x27)
0000: RCPT TO:< test456@mydomain.com>
<= Recv SSL data, 0x5 bytes (0x5)
0000: .....
<= Recv header, 0x4e bytes (0x4e)
0000: 553-5.1.2 The recipient address < test456@mydomain.com> is
0x40:  not a valid
<= Recv header, 0x38 bytes (0x38)
0000: 553 5.1.2 RFC-5321 address. v126sm849160pfb.60 - gsmtp
== Info: RCPT failed: 553=> Send SSL data, 0x5 bytes (0x5)

**Comment by nickorr** [comment]
Howard,

We can't repeat this, in our tests it works as expected.  Are you sure there's not a non-printing character at the start of the email address?

If not, are you able to give me a sample file I can test with.  Send it to nick@goya.com.au

Thanks,
Nick
