### ISSUE TITLE
RegEx not working as expected

### ISSUE THREAD

**Issue by nilswald** [GoyaPtyLtd/BaseElements-Plugin#122]
Hi,

may be I am doing something wrong here but according to [this RegExr example](http://regexr.com/3dqp9) it should be working. 

I am trying to extract filenames from a ftp file list:

```
-r--r--r--   1 u3116    (?)      47819684 Apr 15 22:34 20160415_group_all_covers-0300px-001.zip
-r--r--r--   1 u3116    (?)       1092812 Apr 15 22:34 20160415_group_all_covers-0300px-002.zip
-r--r--r--   1 u3116    (?)      106649625 Apr 15 22:34 20160415_group_all_covers-0600px-001.zip
-r--r--r--   1 u3116    (?)       3416550 Apr 15 22:34 20160415_group_all_covers-0600px-002.zip
```

by using `BE_RegularExpression ( $list; "(?:\S(?![ ]))+$"; "igm" )` but I get an empty result. With only a single line of input and no \r at the end the filename ist returned. When I substitute ¶ for char(10) at least the first filename in the list is returned as if the global 'g' was ignored.

Any ideas welcome

Nils

**Comment by nickorr** [comment]
Nils,

Are you encoding the \ in the text for FileMaker?  The git issues page is really for issues with compiling or the C code.  For general plugin questions we have the paid support option : http://www.goya.com.au/baseelements/plugin/sponsors

Cheers,
Nick
