### ISSUE TITLE
BE_ExecuteSystemCommand Returns an error when dealing with extended ASCII Characters

### ISSUE THREAD

**Issue by bjarnenoddebo** [GoyaPtyLtd/BaseElements-Plugin#125]
Example:

On Windows Server 2012 R2 using Baseelements 3.2

Get the FullName of an Domain user:

BE_ExecuteSystemCommand ( "wmic useraccount where name='bjn' get FullName" )

If the users name cotains an extended ASCII character the function fails. (-1). If the users name do not contain such a character the FullName is returned alright..

**Comment by nickorr** [comment]
Does the command work normally when executed outside of FMP?  We're only passing this into the command line, so it should behave the same, except for permissions of course.

Cheers,
Nick

**Comment by bjarnenoddebo** [comment]
Hello Nick

Thank you for responding on my post..

As shown in the screen shots the Windows Server returns the result as expected. Something must happen when retrieving the result in FIleMaker

[cid:0B20CD98-83B7-463D-AF79-3DAA03C711C9@waoo.dk]

It is the Danish letter ø in my name that causes the problem..

[cid:8E1F2BC8-2DC4-4D70-8BBE-C2156C20D3B3@waoo.dk]

Regards
Bjarne Nøddebo

Den 17. nov. 2016 kl. 03.27 skrev Nicholas Orr <notifications@github.com<mailto:notifications@github.com>>:


Does the command work normally when executed outside of FMP? We're only passing this into the command line, so it should behave the same, except for permissions of course.

Cheers,
Nick

**Comment by nickorr** [comment]
I didn't get the attachments, can you upload them here.

Thanks,
Nick

**Comment by bjarnenoddebo** [comment]
<img width="540" alt="example 1 be_executesystemcommand" src="https://cloud.githubusercontent.com/assets/23460858/20380919/23758bb0-aca5-11e6-97ec-7aef2a4ee2cd.png">

**Comment by bjarnenoddebo** [comment]
<img width="756" alt="example 2 be_executesystemcommand" src="https://cloud.githubusercontent.com/assets/23460858/20380930/30961a6c-aca5-11e6-9db1-7ed1347332d1.png">

**Comment by nickorr** [comment]
Bjarne,

We've added some extra checking around encoding types and this function.  This will be in the 4.0 branch.

Cheers,
Nick

**Comment by bjarnenoddebo** [comment]
Looking foreward to its release.

**Comment by Carl-Gustaf** [comment]
I have the same issue as @bjarnenoddebo. I'm looking forward for a release!

**Comment by nickorr** [comment]
Carl,

The beta versions get made available to sponsors, along with a support channel.  Please subscribe if that's something you're after.

Cheers,
Nick

**Comment by glitchtracker** [comment]
no the same as #220, #220 still happens
