### ISSUE TITLE
BE_XPath question

### ISSUE THREAD

**Issue by jolrm2016** [GoyaPtyLtd/BaseElements-Plugin#126]
Hello

I’m trying to parse the following xml from Filemaker using the Be-XPath function:

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Body>
<ConsultaResponse xmlns="http://tempuri.org/">
<ConsultaResult xmlns:a="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
<a:CodigoEstatus>S - Comprobante obtenido satisfactoriamente.</a:CodigoEstatus>
<a:Estado>Cancelado</a:Estado>
</ConsultaResult>
</ConsultaResponse>
</s:Body>
</s:Envelope>

I need to obtain a:CodigoEstatus and a:Estado, so the parameters I entered for a:CodigoEstatus are:

BE_XPath ( $xml ; "/s:Envelope/s:Body/ConsultaResponse/ConsultaResult/a:CodigoEstatus"; 
"s=http://schemas.xmlsoap.org/soap/envelope/ a=http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio" )

This function doesn’t return a value, what I’m doing wrong?

Thanks, in advance.

**Comment by jteich7** [comment]
[namespace for ConsultaResponse (and others) is missing] This is not the right place for user questions ...

Jens

**Comment by nickorr** [comment]
You're missing the namespace for the ConsultaResponse in the path.

For plugin support we have a sponsor option : http://www.goya.com.au/baseelements/plugin/sponsors

Cheers,
Nick
