### ISSUE TITLE
BE_StripMXLNodes error

### ISSUE THREAD

**Issue by laurabowyer** [GoyaPtyLtd/BaseElements-Plugin#127]
Hello:

I am working on a FileMaker11 conversion to FM15 32 bit. I've run a few BE reports along the way with no issue. After I converted the files and tried to run a BE report I am getting the attached error. I tried recovering the file, checking for permissions, etc, but cannot find the issue.

Thanks in advance for your assistance.
Laura 

![beerror](https://cloud.githubusercontent.com/assets/16767573/20907534/baf5e8ec-bb03-11e6-9d5d-4c9863bc8988.JPG)

**Comment by nickorr** [comment]
Laura,

Github is for tech issues to do with compiling the plugin.  Use support@baseelements.com for BE related questions.

Cheers,
Nick
