### ISSUE TITLE
BE_SMTP_Send CURL Error 2

### ISSUE THREAD

**Issue by bmangus** [GoyaPtyLtd/BaseElements-Plugin#128]
I am attempting to attach a file (using BE_SMTP_AddAttachment) from a container field and send it with an email using BE_SMTP_Send. I can get a test email to send just fine without the attachment parameter. Once I add the attachment parameter, the function fails (no result from the BE_Curl_Trace function) and I get an error code 2 returned from BE_GetLastError. 

I am using version 3.3.3 of the plugin, in FileMaker Pro Advanced 15.0.3 on MacOS Sierra. Below is the code:

Let([
~server = BE_SMTP_Server ( "smtp.gmail.com"  ; 587 ; "PRIVATE" ; "PRIVATE" );
~attach = BE_SMTP_AddAttachment ( OrderItems | Orders | Donation Letter Queue::DonationLetter );
~opt = BE_Curl_Set_Option ( "BE_CURLOPT_FORCE_STARTTLS" ; True );
~send = BE_SMTP_Send ( "PRIVATE" ; "PRIVATE" ; "test" ; "Test Email" ; "" ; "" ; "" ; "" ; ~attach  );
$$error_num = BE_GetLastError;
];
BE_Curl_Trace
)

**Comment by bmangus** [comment]
It appears that the file format I used for testing (FileMaker snapshot link) is not supported. However, I do not see any documentation specifying supported or unsupported files (at the link below), so I will leave this open to make sure it is not a bug. I was able to use the code above with a PNG image, but not with a FileMaker snapshot link. 

https://baseelementsplugin.zendesk.com/hc/en-us/articles/224605868-BE-SMTP-AddAttachment

**Comment by nickorr** [comment]
bmangus,

The GitHub issues page is not for support, more for compiling or code issues.  https://baseelementsplugin.zendesk.com/hc/en-us/articles/115001543347-What-is-plugin-sponsorship-

Try writing the file to disk first instead of attaching from the container field.

Cheers,
Nick
