### ISSUE TITLE
BE_HTTP_POST is broken with payload containing "=@"

### ISSUE THREAD

**Issue by ericscheid** [GoyaPtyLtd/BaseElements-Plugin#131]
I'm using the plugin to BE_HTTP_POST to a JSON API, and stumbled into this stumper ..

The JSON text I'm sending contains the following bit of HTML text:

    <a href="https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p=@NT08=UFQxUlRRPT0=NjJ">https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p=@NT08=UFQxUlRRPT0=NjJ</a>

The API I'm hitting is reporting an error of cannot parse as JSON. When I submit it to a simple reflector API I can see this as the headers and post body:

    Connection: close
    Content-Type: application/json; boundary=------------------------c13abbc37c9d3711
    Expect: 100-continue
    Content-Length: 521
    Accept: */*
    User-Agent: libcurl-agent-base-elements-plugin/3.3
    Host: kano.io

    --------------------------c13abbc37c9d3711
    Content-Disposition: form-data; name="{
      "options": {
        "click_tracking": false,
        "open_tracking": false,
        "transactional": true
        },
      "content": {
        "from": {
          "name": "redacted",
          "email": "redacted@redacted.org"
        },
        "subject": "FW: Strategic Mobile Project Informal Market Engagement",
        "html": "<a href"

    \"https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p
    --------------------------c13abbc37c9d3711--

You can probably see a problem or two there.

If I change the HTML code such that the `@` is urlencoded as `%40`, the reflector shows that this is what was sent:

    Connection: close
    Content-Length: 670
    Content-Type: application/json
    Accept: */*
    User-Agent: libcurl-agent-base-elements-plugin/3.3
    Host: kano.io

    {
      "options": {
        "click_tracking": false,
        "open_tracking": false,
        "transactional": true
        },
      "content": {
        "from": {
          "name": "redacted",
          "email": "redacted@redacted.org"
        },
        "subject": "FW: Strategic Mobile Project Informal Market Engagement",
        "html": "<a href=\"https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p=%40NT08=UFQxUlRRPT0=NjJ\">https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p=%40NT08=UFQxUlRRPT0=NjJ</a>",
        "attachments": [  ]
      },

      "recipients": [{
        "address": {
          "name": "Eric Scheid",
          "email": "redacted@redacted.com"
        }
      }]
    }

Which is exactly what is expected to be sent, and which works with the target API.

----

Further, if I change the JSON payload such that it doesn't have the URL with `p=@text` repeated, like this:

    Copy/paste this link: https://www.contractsfinder.service.gov.uk/Notice/c6915c39-1014-4588-8550-b58f33b8aa1f?p=@NT08=UFQxUlRRPT0=NjJ

then the call to BE_HTTP_POST completely fails, returning simply "?" as the result. 

A call to `BE_GetLastError` produces `26`, which is apparently "[a read error. It failed to read/access a file you pointed out to curl](https://curl.haxx.se/mail/archive-2011-04/0038.html)" if that helps.

A call to `BE_Curl_Trace` produces this:

    == Info:   Trying 64.111.124.115...
    == Info: Connected to kano.io (64.111.124.115) port 80 (#0)
    == Info: couldn't open file "NT08"
    == Info: Closing connection 0

So, something screwy is going wrong in the bowels of the BE_HTTP_POST function. Probably some content is not being properly escaped when it is being piped to `curl`.

**Comment by ericscheid** [comment]
Oh look, `NT08` is directly mentioned in the URL string `?p=@NT08...`

**Comment by ericscheid** [comment]
Just downloaded 3.3.2, quit, installed, launched, and regressed. Problem persists.

**Comment by ericscheid** [comment]
BaseElements v3.1 contains this change log:

    BE_HTTP_POST: allow post args to specify file paths using the @ syntax

**Comment by dansmith65** [comment]
RFC 3986 specs for a URI state that `@` is a reserved character and must be percent encoded if it's not being used as a delimiter: https://tools.ietf.org/html/rfc3986#section-2.2. If the two `=` that follow NT08 are part of the value instead of a delimiter, they should be percent encoded as well.

**Comment by ericscheid** [comment]
Yup, I got lucky this time as the substring "=@" was in a URL and could thus be rewritten for effect.

Here is another payload that fails:
> `Here is a magic string: FOO=@NT08=UFQx=NjJ&BAR=@NT08=UFQx=ABC`

Here is the BE_Curl_Trace
> == Info:   Trying 64.111.124.115...
> == Info: Connected to kano.io (64.111.124.115) port 80 (#0)
> == Info: couldn't open file "NT08"
> == Info: Closing connection 0
