### ISSUE TITLE
BE_SMTP_AddAttachment/BE_SMTP_Send, defective attachments

### ISSUE THREAD

**Issue by t-andersen** [GoyaPtyLtd/BaseElements-Plugin#132]
(BE 3.3.4, MacOs 10.10.5, FM 14.06 ADV, FM 15.02 ADV)

**Indication**
Having problems with attachments being defective. 
The emails look fine, and the attachments seems to be correctly added to the email. However, when trying to open the attachments they will not open due to a file error. 
I have noticed that the attachments enclosed in the emails are only a few kB, even if the original files in the container are 250kB or more.
It looks as if the error occurs during writing the container file to disk since the size is only a fraction of the originals.

**Remedies tried**
Tried with several different file types. 
Tried on two different machines, with both internal and external containers. 
/tmp folder verified with read/write access to system, wheel and everyone. 
Permissions repaired with DiskUtility.

**Comment by ND83** [comment]
French user I just discovered that plugin and its various functions. I can use it to send mails but I don't understand how to link attachments. I don't understant the explanation found on the site 

> " BE_SMTP_AddAttachment ( container ) Stores a list of container field files as attachments for future SMTP_Send functions.
> 
> > Parameters : 
> > container : a container field with a file to be sent to the next mail via SMTP.
> > Use this function to add attachments to an outgoing email that would normally be sent via SMTP Send, but are not on disk.  You can add multiple attachments by calling this multiple times.  Once SMTP_Send is done it clears out the list of stored attachments regardless of the success of the Send.
> > Attachments are actually written to disk by the plugin, to the users temp folder, so this does require you to have access to a working temp folder ( defined by the OS ). "

Actually I have the paths of the files I want to attach in a text field as this 

> /Users/nd/Desktop/sapad_farlède/Programme30032018.pdf
> /Users/nd/Desktop/Recuperer.log
> Volumes/MacND/Users/nd/Documents/DATAS_ADH_PEP/UPLOAD/courriers.csv

Can you help me please ?
Regards

**Comment by nickorr** [comment]
ND83,

Git issues is for issues with the C code in the plugin, or questions about compiling it.  If you need implantation support for the plugin, please consider a sponsorship.

Thanks,
Nick
