### ISSUE TITLE
BE_HTTP_GET possible memory leak/corruption ?

### ISSUE THREAD

**Issue by glitchtracker** [GoyaPtyLtd/BaseElements-Plugin#133]
Hi,

I encountered a FMSE crash an reported it here

https://community.filemaker.com/message/682016?et=watches.email.thread#682016

Take a look at what  MBS Christian says

"On cleanup of CURL data structures in BaseElements plugin crashes here.
A memory block is freed which was never allocated.
 
As this is within a standard C++ class, I expect some memory corruption, e.g. one function overwrite memory it doesn't own."

Here's the crashed thread part

Thread 57 Crashed:
0   libsystem_kernel.dylib        	0x00007fffb7287dda __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffb7372797 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffb71ed440 abort + 129
3   libsystem_malloc.dylib        	0x00007fffb72dd097 free + 530
4   libstdc++.6.dylib             	0x00007fffb6ecb2d0 std::string::assign(std::string const&) + 114
5   au.com.goya.baseelements      	0x000000011398878d BECurl::cleanup() + 157
6   au.com.goya.baseelements      	0x000000011398781e BECurl::perform_action() + 1038
7   au.com.goya.baseelements      	0x0000000113942eac BE_HTTP_GET(short, fmx::ExprEnv const&, fmx::DataVect const&, fmx::Data&) + 700
8   com.filemaker.dbengine.framework	0x000000010dfa5d9f Draco::DBCalcSolver::SolvePlugins(Draco::DBError&) + 1107
9   com.filemaker.dbengine.framework	0x000000010dfa0d61 Draco::DBCalcSolver::SolvePolish(Draco::DBDataArg&, unsigned short) + 4371
10  com.filemaker.dbengine.framework	0x000000010df703bc Draco::DBCalcFormula::Solve(Draco::DBData&, Draco::DBCursor const*, Draco::DBCursor const*, Draco::DBData const*, Draco::DBFieldSpec const*, Draco::DBField const*, unsigned short) const + 738
11  com.filemaker.fmengine.framework	0x000000010e98c589 Draco::FMWindowModel::SolveCalculation(Draco::DBData&, Draco::DBCalcFormula*, short, bool, Draco::DBCursor const*) + 209
12  com.filemaker.fmengine.framework	0x000000010e9930d1 Draco::ScriptRuntimeBase::SolveCalculation(Draco::DBData&, short, short, bool, Draco::DBCursor const*, Draco::FMWindowModel*, bool) + 157
13  com.filemaker.fmengine.framework	0x000000010e9961e8 Draco::ScriptRuntimeBase::DoSetVariable(Draco::unistring*) + 596
14  com.filemaker.fmengine.framework	0x000000010e994398 Draco::ScriptRuntimeBase::Execute() + 1450
15  com.filemaker.fmengine.framework	0x000000010e993d59 Draco::ScriptRuntimeBase::DoNextStep() + 313
16  com.filemaker.fmengine.framework	0x000000010e993bb9 Draco::ScriptRuntimeBase::DoRunLoop() + 203
17  com.filemaker.fmengine.framework	0x000000010e9b78f4 Draco::SMScriptRuntime::OnIdle() + 102
18  com.filemaker.fmengine.framework	0x000000010e9812a7 Draco::FMSession::OnIdle(bool) + 69
19  com.filemaker.fmengine.framework	0x000000010e9b8d9f Draco::SMSession::Idle() + 71
20  com.filemaker.fmengine.framework	0x000000010e9b71b3 Draco::SMScriptRuntime::CompleteScript(Draco::unistring*) + 107
21  com.filemaker.fmengine.framework	0x000000010e9b75c7 Draco::SMScriptRuntime::ExecuteScript(Draco::SMFileUser&, Draco::unistring const&, Draco::unistring const&, Draco::unistring*) + 467
22  com.filemaker.fmengine.framework	0x000000010e9b9063 Draco::SMSession::RunScriptAndClose(Draco::UniversalPath const&, Draco::DBAuthenticationInfo&, Draco::unistring const&, Draco::unistring const&, Draco::unistring*) + 689
23  fmsased                       	0x000000010d8e55e9 FMScriptThread::RunScript(FMSTypes::ScriptMakerOperation const*, Draco::DBAuthenticationInfo&) + 339
24  fmsased                       	0x000000010d8e51a0 FMScriptThread::Main() + 494
25  com.filemaker.support.framework	0x000000010f484cc7 Draco::Thread::RunThread() + 59
26  com.filemaker.support.framework	0x000000010f483d59 Draco::Thread::ThreadUnixProc(void*) + 51
27  libsystem_pthread.dylib       	0x00007fffb736fabb _pthread_body + 180
28  libsystem_pthread.dylib       	0x00007fffb736fa07 _pthread_start + 286
29  libsystem_pthread.dylib       	0x00007fffb736f231 thread_start + 13

**Comment by nickorr** [comment]
glitchtracker,

Thanks.  As per my reply on the thread, this is due to the plugin not being thread safe.  The only way to safely run BE on a server is to only have a single instance running at a time.  This is something we're considering changing in a future build.

Cheers,
Nick
