### ISSUE TITLE
BE_SMTP_SEND missing DATE field in Header

### ISSUE THREAD

**Issue by victorpolyak** [GoyaPtyLtd/BaseElements-Plugin#134]
**Plugin version 3.3.0**
**Filemaker PRO and Advanced 15**
**Windows Server 2008 R2**

**Issue:**
Sending email with BE_SMTP_SEND have a missing header field DATE which causes emails not being delivered or delivered with incorrect date based on the email client.

Would be great to have that fixed.

P.S. Many thanks for your great plugin!

Below are two headers 1 - via plugin 2 - via native Filemaker send mail function.

![image](https://user-images.githubusercontent.com/30897622/29168921-844c5f9c-7dd1-11e7-9297-b7adcb5bfd90.png)

**Comment by nickorr** [comment]
This functionality is in the 4.0 branch already.  A beta is available to sponsors, and the final will be made public when it's ready.

Cheers,
Nick
