### ISSUE TITLE
BE_HTTP_POST breaks over time

### ISSUE THREAD

**Issue by beargie** [GoyaPtyLtd/BaseElements-Plugin#135]
There was an update for BE_HTTP_POST in v3.3.5 that addressed an issue where BE_HTTP_POST responses were erroring out.

While the 3.3.5 update has corrected the initial issue, if you wait for about 10 minutes after the first BE_HTTP_POST call is made and attempt any further calls, the old error returns.

We get an error response that looks something like this:
{"Message":"The requested resource does not support http method 'GET'."}
HTTP/1.1 405 Method Not Allowed

I am attaching a full version of our function call with the URLs obfuscated. We have confirmed that the issue resolves by restarting filemaker, however that is not a long term solution.

In the log around line 182, you can see it outputs that it is sending a GET request, but we never specify it as GET, and use BE_Curl_Set_Option ( "CURLOPT_POST" ) as well to try and force POST.

Any ideas on probable cause, or is there any way to force BE itself to reload?

[BaseElementsErrorLog.txt](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/1260882/BaseElementsErrorLog.txt)

**Comment by nickorr** [comment]
Mike,

We had another issue with 3.3.5 and POST, and we've done a 3.3.6 since then.  Does the issue still remain in that release?

Cheers,
Nick

**Comment by beargie** [comment]
Hi Nick,

Yes, it appears we were not aware of the update and the timeout is resolved with 3.3.6

Thanks!
Mike

**Comment by beargie** [comment]
Just received reports and confirmed that the timeout issue re-appeared. Confirmed.

However in 3.3.6 the timeout now seems to be around half an hour instead of 10-15 minutes.

Same error message as before, where it's apparently trying to use GET instead of POST

**Comment by nickorr** [comment]
Mike,

Git is really for programming or compiling issues.  Can you send a bug report to support@freefilemakerplugin.com and I'll process it there.

Can you include a sample file, that shows the issue that we can test against.

Thanks,
Nick
