### ISSUE TITLE
Embedded Python

### ISSUE THREAD

**Issue by chivalry** [GoyaPtyLtd/BaseElements-Plugin#136]
This is probably a pie-in-the-sky wish, but I would love to see a FileMaker plugin with embedded Python 3. I haven't looked at the source code for BE yet, but you already have `BE_EvaluateJavaScript`. I'd love to see `BE_EvaluatePython`.

**Comment by nickorr** [comment]
You know, it's actually something I've considered as well.  I have no idea how viable it is, but I'll add it to the ideas list.

It will be a while, unless you're interested in directly sponsoring it.

Cheers,
Nick

**Comment by chivalry** [comment]
Sponsoring it wouldn't be a financial option for me, but I'll take a look at the source code and see if I can help implement it. I've done some plugin programming before, but it's been Mac only using Objective-C++. I'll fork the project and see what I can come up with.
