### ISSUE TITLE
Missing libboost_atomic.a

### ISSUE THREAD

**Issue by Nicolaik** [GoyaPtyLtd/BaseElements-Plugin#141]
I am trying to build 4.0b5 release

OSX 10.12.6, Xcode 9.1
iMac (21.5-inch, Late 2013), 2.7 GHz Intel Core i5

I downloaded Boost 1.61.0 from https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.zip/download

No errors running ./bootstrap.sh and ./b2 with parameters as specified in Building.macOS for the release

I have five .a files in my boost_1_61_0/build/lib. They are:

libboost_date_time.a
libboost_filesystem.a 
libboost_regex.a
libboost_system.a
libboost_thread.a

In Xcode project there is another file listed, libboost_atomic.a which is not present in the build. I tried to build the latest Boost release (1.66.0) with the same result.

Is there  flag missing for b2 or the library no longer needed and could be removed from the project?

**Comment by minstral** [comment]
Thanks Nicolaik for the report and harawata for the patch.

**Comment by Nicolaik** [comment]
Than you, Mark
