### ISSUE TITLE
 Jansson library build path

### ISSUE THREAD

**Issue by Nicolaik** [GoyaPtyLtd/BaseElements-Plugin#142]
4.0b5 release
OSX 10.12.6, Xcode 9.1
iMac (21.5-inch, Late 2013), 2.7 GHz Intel Core i5

Building Jansson - 2.5 from https://github.com/GoyaPtyLtd/jansson

When using ./configure --prefix=build CFLAGS="-mmacosx-version-min=10.7" as in documentation getting an error:

_configure: error: expected an absolute directory name for --prefix: build_

Unlike ./b2, ./configure on my computer does not take relative locations for _--prefix_ parameter

I also tried _--prefix=/build_ which results in the successful build in root directory (with sudo for make install) and _../build_ which produces the same error as above

I specified the --prefix as the full path to the build directory and the build ran successfully

Suggestion:	change the document Building.macOS line

`	./configure --prefix=build CFLAGS="-mmacosx-version-min=10.7"`
	
into
	`./configure --prefix=<full/path/to/build/directory> CFLAGS="-mmacosx-version-min=10.7"`
or something similar.
Also, the last line for Jansson reads as 

Copy jansson.h and jansson_config.h from build/include to the Headers directory and  
build/lib/libjansson.a to Libraries/osx.

To match the project folder structure this should be 	

Copy jansson.h and jansson_config.h from build/include to the Headers directory and  
build/lib/libjansson.a to Libraries/**macOS**.

**Comment by Nicolaik** [comment]
Also tried ./build for prefix, still the same error

**Comment by minstral** [comment]
Thank you Nicolaik for the original reports and harawata for the patch.
