### ISSUE TITLE
liboauth - 1.0.3 missing build target folder

### ISSUE THREAD

**Issue by Nicolaik** [GoyaPtyLtd/BaseElements-Plugin#143]
4.0b5 release
OSX 10.12.6, Xcode 9.1
iMac (21.5-inch, Late 2013), 2.7 GHz Intel Core i5

	./configure CFLAGS="-mmacosx-version-min=10.7"
performs system level install. I think, it needs build destination
	
Suggestion: change to

	./configure CFLAGS="-mmacosx-version-min=10.7" --prefix=<full/path/to/build/directory>

**Comment by harawata** [comment]
Hi @Nicolaik ,

Most issues you reported should be fixed by #150 .
Could you check the [updated build guide](https://github.com/GoyaPtyLtd/BaseElements-Plugin/blob/development/BUILDING.macOS) and close the resolved issues when you have time, please?

Thank you!

**Comment by Nicolaik** [comment]
Thanks, will do.

**Comment by Nicolaik** [comment]
This is changed to 

```
./configure CFLAGS="-mmacosx-version-min=10.7"
make
```

First of all, _sudo make install_ is missing after _make_. Also, does _make_ on it's own is really necessary?

Am I doing something wrong, because without specifying the install directory I have build directory set in  **/usr/local/** ?

**Comment by harawata** [comment]
I guess the build process for liboauth is a little bit different from the other libraries and the library file we need (liboauth.a) is generated in `./src/.libs` by executing `make`.
So `make` is necessary, but `make install` is not.

**Comment by Nicolaik** [comment]
Thanks, @harawata

I played with my environment a bit and at some point my autoconfig tools were manually installed with curl. xcode-select --install probably did not overwrite everithing

In any case, I have the library successfully built

I am closing the issue, if you don't mind

**Comment by harawata** [comment]
Thank you for verifying it, @Nicolaik !
