### ISSUE TITLE
Building OpenSSL - 1.0.2g

### ISSUE THREAD

**Issue by Nicolaik** [GoyaPtyLtd/BaseElements-Plugin#146]
4.0b5 release
OSX 10.12.6, Xcode 9.1
iMac (21.5-inch, Late 2013), 2.7 GHz Intel Core i5

A few minor points about instructions in BUILDING.macOSX

>  ./Configure darwin64-x86_64-cc -mmacosx-version-min=10.7 --prefix=/Users/mark/Desktop/openssl/build
 
This need to change Mark's absolute file path to generic one
 
  _./Configure_ asked me to run make depend before make install. This is probably related to me downloading zip of the OpenSSL archive release instead of pulling it with git
  
> Copy libcrypto.a and libssl.a to Libraries/macOS and copy build/include/openssl to Headers.  

I suggest adding <build directory>/lib for clarity:

`  From <build directory>/lib copy libcrypto.a and libssl.a to Libraries/macOS and copy build/include/openssl to Headers.  `

**Comment by Nicolaik** [comment]
That's perfect. I do love the new approach with ${SRCROOT}, $(pwd) and cp.

The instructions got much clearer and better organised as well.

**Comment by harawata** [comment]
Thank you for the nice words, @Nicolaik !
It's not much compared to writing it from scratch, but I'm glad you liked it. =)
