### ISSUE TITLE
Setting guidelines for repository contributors

### ISSUE THREAD

**Issue by dansmith65** [GoyaPtyLtd/BaseElements-Plugin#156]
You might want to consider adding this to your repo: https://help.github.com/articles/setting-guidelines-for-repository-contributors/. It might make it more obvious to users about the intended use of GitHub issues.

You could also suggest https://fmforums.com/forum/56-filemaker-plug-ins/ for community-supported help.

**Comment by nickorr** [comment]
Dan,

This is a great idea.  We've had this discussion internally around some of the recently submitted functions, so it's timely as well.

Thanks,
Nick
