### ISSUE TITLE
Getting zero length file from Export

### ISSUE THREAD

**Issue by rwu2359** [GoyaPtyLtd/BaseElements-Plugin#157]
Using BE_ExportFieldContents on a windows server, the file is created from the container but has a zero length, which is not quite as useful as first imagined.

This is with 3.3.7 on WinServer 2012

**Comment by DavidWikstrom** [comment]
Hi John!

I'm using this successfully and have been doing so for quote some time in various solutions over the years. Can you please provide more details on the file path you're exporting to, the file your are exporting, or what not? What do you get from BE_GetLastError and BE_GetLastDDLError?

I've had 0 byte files created when doing FTP without opening the firewall properly - kind of different, but maybe it can be some kind of permissions issue?!

/David
