### ISSUE TITLE
Can't send email to multiple recipient list on plugin version 4.0

### ISSUE THREAD

**Issue by mhtawfiq** [GoyaPtyLtd/BaseElements-Plugin#158]
On version 4.0 when using BE_SMTP_Send to send to a list of recipients  "one@dom.com¶two@dom.com", BE_GetLastError returns 55 and the email fails.

The same function works fine on plugin version 3.3.7

**Comment by nickorr** [comment]
Can you check with 4.0.1 which is the newly linked download version.

Cheers,
Nick

**Comment by mhtawfiq** [comment]
Fixed in 4.0.1

Thank you!
