### ISSUE TITLE
Request to keep BE_JSON* functions in version 4 if possible

### ISSUE THREAD

**Issue by mhtawfiq** [GoyaPtyLtd/BaseElements-Plugin#159]
All the BE_JSON* functions have been deprecated and removed in plugin version 4.

While FM16+ has native JSON functions that do the same work, I would request to keep BE_JSON* functions in version 4 for the following reasons:

- The BE_JSON* functions are faster than native FM functions when dealing with larger sizes of JSON data and sometimes i end up using both native and BE_JSON functions together for better performance.
- I use BEPlugin BE_JSON* functions in FM14/15 solution that are unlikely to upgrade and this means they will always need version 3.3.7 of the plugin

If not possible, then at least keep 3.3.7 (win32/win64/mac) publicly downloadable.

While i have access to the shared Dropbox folder to download any version, only win32 version is publicly downloadable at the moment.

Thank you.

**Comment by nickorr** [comment]
Please send all these sorts of requests to the main support site https://baseelementsplugin.zendesk.com/hc/en-us.

The JSON functions are deprecated, meaning they no longer appear in the list, but are still there and work fine, and can be used.  I don't plan to remove them for a while, but we're suggesting people use the internal v16 ones instead.

I'll add v3.x links to the download page too.

Cheers,
Nick
