### ISSUE TITLE
BE_ExportFieldContents returning $osPath

### ISSUE THREAD

**Issue by pereljon** [GoyaPtyLtd/BaseElements-Plugin#160]
A solution updated to BE Plugin to 4.0.1 started failing, and I traced it down to BE_ExportFieldContents not returning the expected results. It seems to be returning the outputPath now, instead of empty for success. I fixed it by ignoring the result and getting the error from BE_GetLastError. Is this new functionality, because it doesn't match the documentation.

This is running on Windows 2016, FileMaker Server 16 (latest updates), under a FMSE script.

Cheers,
JP

**Comment by nickorr** [comment]
Thanks this was a deliberate change to allow more functionality, I’ll update the docs to explain tomorrow.

Cheers,
Nick
