### ISSUE TITLE
BE_RegularExpression: dot matched /r by default

### ISSUE THREAD

**Issue by davidmartincodes** [GoyaPtyLtd/BaseElements-Plugin#161]
We're running Filemaker Server 17 on Windows Server 2016 and using BaseElements-Plugin 4.0.2. I've had some difficulty using the BE_RegularExpression function, as it was obtaining multiple lines from the referenced field, and discovered that the feature was dot matching /r by default.

I discovered this by testing the following function to determine the character code used for Paragraph

`Char ( ¶ )` =  unicode 13

Coming from Filemaker Server 12 on Windows Server 2008 R2, this surprised me because I've used an earlier edition of the plugin there without issue, and I knew that ¶ was unicode 10 (/n) in that environment.

When I converted the ¶ to unicode 10 (/n), BE_RegularExpression functioned appropriately. Unfortunately, Filemaker Server 17 on Windows Server 2016 appears to default to unicode 13 for new lines, and would take substantial work to ensure everything is converted to unicode 10 (/n).

Is it possible to modify the function so that it does not match /r with dot?

**Comment by nickorr** [comment]
Following up on an old question.  The functions work as is, and are often dependent on the base library we use.  There are lots of variations in OS, line endings, character sets, and I'm reluctant to change an existing function like this.

If you'd like to see something more happen, or a new function, please consider being a sponsor.

Thanks,
Nick
