### ISSUE TITLE
Wrong sent date using BE_SMTP_Send on FileMaker Server 17

### ISSUE THREAD

**Issue by gageler** [GoyaPtyLtd/BaseElements-Plugin#162]
I am not sure if others have has this issue, but when I send an email using the BE_Plugin from FileMaker Server (17) [Windows 2016], the date sent in the email is incorrect. It is stuck on a date about 6 weeks ago and is never the current date/time.

When the same script is triggered using the plugin on a client (FileMaker Pro Advanced 17) we have no issue - the date is correct.

Also, when we use the native Send Mail script command, emails issued from FMS have the correct date.

Is is possible that the Plugin is somehow passing a cached date, even though there is no date parameter in the way the plugin function is used? 

Phillip Gageler

**Comment by gageler** [comment]
Sorry, I just realised that the change log suggests that this issue was addresses in version 4.0.3 (9 October 2018).
But it seems that the latest downloadable version is still on 4.0.2.
Is 4.0.3 available for use anywhere?
Phillip

**Comment by nickorr** [comment]
4.0.3 is now up on the website and dropbox.

Cheers,
Nick

**Comment by gageler** [comment]
Thanks Nick.


Phillip Gageler
Sent from my iPhone

On 16 Oct 2018, at 5:33 pm, Nicholas Orr <notifications@github.com<mailto:notifications@github.com>> wrote:


4.0.3 is now up on the website and dropbox.

Cheers,
Nick

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GoyaPtyLtd_BaseElements-2DPlugin_issues_162-23issuecomment-2D430169347&d=DwMCaQ&c=OKOU6Ppfkbydpsmij-EjMgkb3qYqv8fdeJ_JvSTSY-8&r=J-QhsFJnsEqkgxCwgn-pQPSX24EPXWu6DEuIu9KEdQQ&m=Eq_FgjQg5t-ULNpQ8cdZDoZUTRW4W-YIPWMMg75GoPw&s=Tn39saVJwgfPHG1234Ti51sOmEIGl_85HX-GSyfBysA&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AqIzjEmshjnfsA-2DIpZH3HMm3g-2DI0Mj2Eks5ulafTgaJpZM4XddLK&d=DwMCaQ&c=OKOU6Ppfkbydpsmij-EjMgkb3qYqv8fdeJ_JvSTSY-8&r=J-QhsFJnsEqkgxCwgn-pQPSX24EPXWu6DEuIu9KEdQQ&m=Eq_FgjQg5t-ULNpQ8cdZDoZUTRW4W-YIPWMMg75GoPw&s=3bq7g9TKqcrXfIWn0_0IFQmdTaKkCbQvDF006AGXLQ0&e=>.

This e-mail message may contain confidential or legally privileged information and is only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. GFG Alliance and its related bodies corporate and the sender are not responsible for errors or omissions in this message and deny any responsibility for any damage arising from the use of this e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company. All and any rights as to confidentiality, legal professional privilege and copyright are expressly reserved.

**Comment by gageler** [comment]
Sorry Nick - I just went to download it using the link on https://baseelementsplugin.zendesk.com/hc/en-us/articles/115002990887 (to: http://www.goya.com.au/files/beplugin/current/BaseElements.fmx64.zip) and the Windows 64 bit Version still the previous version - with a last modified date of 18 July 2018. Am I looking in the wrong place?
Sorry, I am not familiar with the dropbox address.
Thanks Phillip

**Comment by nickorr** [comment]
Just downloaded it now, modified 9th of October...

**Comment by nickorr** [comment]
Steven,

Where are you downloading from?  I just downloaded the Mac version from the links here : https://baseelementsplugin.zendesk.com/hc/en-us/articles/115002990887-BaseElements-Plugin and it's 4.0.3.

The dropbox shares are available to sponsors of the plugin.  We put the beta releases and a bunch of test files there, but the final releases go out to everyone at the same time.  ( and sponsors get access to our ZenDesk support page, and help with implementation etc.  This issues page is really only for help with compiling or coding the plugin. )

Cheers,
Nick

**Comment by stevenadeau2** [comment]
Version number in the info.plist in the package content still says 4.0.2, that's why...
When installed, Filemaker's preferences say 4.0.3

**Comment by stevenadeau2** [comment]
The problem seems to be still present.
On the right, you can see the delivered date is roughly the same as the date header. (first time be_smtpsend executed)
On the left, you can see the delivered date has changed (because I sent it a second time a couple of minutes later), but the date header still remains.
![image](https://user-images.githubusercontent.com/44245447/47164339-e0666f80-d2c5-11e8-91a7-99429f00f089.png)

**Comment by gageler** [comment]
I updated BE_Plugin to 4.0.3 on FileMaker Server 17 (Windows), and since then have been monitoring emails issued via BE_SMTPSEND. Unfortunately, it seems that the send date is stuck on the local (server) timestamp of the last load of the the plugin at Server start-up. So today (Monday), emails are being issued with a Send date/time of last Friday evening, which is when I last rebooted the Server. So the 4.0.3 update appears not to have fixed this issue.

**Comment by stevenadeau2** [comment]
No, I'm saying 4.0.3 did not correct the issue for me. I'm experiencing the exact same behaviour as you described: on the first execution the timestamp is ok, but all subsequent executions are getting the same exact timestamp as the first one.

Did not find any way to "uncache" the timestamp, other than restarting the Filemaker application (or in your case the FMSE).

**Comment by nickorr** [comment]
Thanks, we did fix a bug in 4.0.3 related to dates, but didn't quite fix this one.  It will be in the next release.

Cheers,
Nick

**Comment by dkiriakopoulos** [comment]
Hi Nick,

is 4.04 going to be public as Christmas gift ? :) Thx!

**Comment by mikeoswego** [comment]
We are also suffering from this problem and look forward to its eventual fix.
Thanks!

**Comment by trevorgildersleeve** [comment]
Same issue. We're doing weekly restarts of the FM Server until a fix is released. 
We were experiencing mail bounces as well:
host XXX said: 550
Date header far in the past/future. (in reply to end of DATA command)

**Comment by dkiriakopoulos** [comment]
it was fixed yesterday in 4.04
