### ISSUE TITLE
BE_XSLT_ApplyInMemory not working

### ISSUE THREAD

**Issue by ibrahim-bittar** [GoyaPtyLtd/BaseElements-Plugin#164]
Hi Nick

A few months ago I successfully made a XSLT transformation but now it doesn't work. It's the same calculation but it's not working. I don't know if it is something on my copy of the plugin or what but it's just not working.

Actually the function is returning an empty string. Please find attached the filemaker file I'm using for testing.
[Cadena Original.zip](https://github.com/GoyaPtyLtd/BaseElements-Plugin/files/2517021/Cadena.Original.zip)

**Comment by nickorr** [comment]
Ibrahim,

I'll have a look at the file, but can you post this on the Plugin support site instead : https://baseelementsplugin.zendesk.com/hc/en-us

Github issues is for issues when compiling the plugin or using the source code.

Thanks,
Nick
