### ISSUE TITLE
BE_ExecuteSystemCommand returns "?"

### ISSUE THREAD

**Issue by ericgarig** [GoyaPtyLtd/BaseElements-Plugin#166]
Using BE_ExecuteSystemCommand to iterate through folders of files to get metadata on each file. After some number of files, the function returns "?" for every command ( It looks like the plugin is failing to release recourses ). In addition, when opening the terminal, I am prompted with 'Resource temporarily unavailable' message. Quitting and restarting FM seems to resolve the issue.

Environment:
OS X 10.12.6
FMA 17.0.2.205
BE plugin 3.3.1

**Comment by nickorr** [comment]
ericgarig,

Can you update to the most recent release and test again.

Thanks,
Nick

**Comment by ericgarig** [comment]
Nick,

Updated to 4.0.3.
Still getting the same issue. This happens around 4500-6000 calls. I have tried it with and without a timeout parameter.

Erik

**Comment by nickorr** [comment]
Can you document the call that you're using?  So I'm curious about the command line ( leave out passwords etc, but include all the info ) and also the timeouts, or not.

Thanks,
Nick

**Comment by ericgarig** [comment]
I must have missed your reply. Below are all of the calls that run as past of a scripts that looks over the contents of a folder ( and subfolders recursively ) and gathers info about image/media files.

The used variables are:
 - `$pathSys_WorkingDir` is a system path to a directory. 
 - `$pathSys_working` is a system path to a file
 - `$timeoutMilliseconds` is 30 seconds

The calls are:
 - `BE_ExecuteSystemCommand ( "find " & Quote ( $pathSys_WorkingDir ) & "  -type f -maxdepth 1 -exec basename {} \; | grep -v  '\r'" ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "find " & Quote ( $pathSys_WorkingDir ) & "* -type d -maxdepth 0 | cut -c " & Length ( $pathSys_WorkingDir ) + 1 & "-" ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "basename " & Quote ( $pathSys_working ) ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "md5 -q " & Quote ( $pathSys_working ) ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "file -b " & Quote ( $pathSys_working ) ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "mdimport " & Quote ( $pathSys_working ) & "; mdls " & Quote ( $pathSys_working ) ; $timeoutMilliseconds )`
 - `BE_ExecuteSystemCommand ( "mdls -raw -name kMDItemKind " & Quote ( $pathSys_working ) ; $timeoutMilliseconds )`

**Comment by nickorr** [comment]
Yep, I can see an issue here.  It seems to be the one where you have a 0 timeout that causes a problem...

We'll investigate and get in touch.

**Comment by nickorr** [comment]
Eric,

We've made a change that reverts this to 4.0.5 behaviour and fixes a crash.  Can you test :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmx64.zip

Cheers,
Nick

**Comment by ericgarig** [comment]
@nickorr - thank you for the update, but I am not working with FileMaker anymore.
I'm tagging the others from the team @DanShockley @jridgway
