### ISSUE TITLE
BE_SMTPAddAttachment fails with iPhone/iPad camera images

### ISSUE THREAD

**Issue by pnortonosi** [GoyaPtyLtd/BaseElements-Plugin#167]
When an IOS device (in my case, an iPad or iPhone) running FileMaker Go 17 saves an image directly from the camera into a container field or from the photo library, using BE_SMTPAddAttachment fails with error 22 when attempting to add the image as an attachment. 

This occurs only when BE_SMTPAddAttachment is run in a scheduled server script. Running the same script on a client (MacOS, FileMaker 16 or 17) the image is attached normally.

Exporting the image from the container field to a hard drive and then importing it back into the container field allows the BE_SMTPAddAttachment to work. In the workaround script, I used BE_ExportFieldContents to export the container field, and then BE_FileImport to bring the image back into the container field. However, manually exporting the field contents from in FileMaker and then dragging the file back into the container field also works.

I have tested this with images stored directly from the camera, and also images pulled from the devices photo library. Neither work. Audio recordings stored directly do work as expected.

The BE_SMTPAddAttachement was used in a script that runs on an a Windows Server 2016, running FileMaker server 17, using the latest BE plugin.

**Comment by nickorr** [comment]
pnortonosi,

Github is for issues compiling the plugin, if you need support, please go here : https://baseelementsplugin.zendesk.com/hc/en-us/articles/115001543347-What-is-plugin-sponsorship-

Cheers,
Nick
