### ISSUE TITLE
bad `CFBundleShortVersionString` causes XCode build failure for iOS SDK

### ISSUE THREAD

**Issue by cristoslc** [GoyaPtyLtd/BaseElements-Plugin#168]
I received the following error in XCode when trying to build an iOS SDK project including BaseElements:
> ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString 'BaseElementsIOS version 4.0.3' in the Info.plist file must be a period-separated list of at most three non-negative integers."

Issue was fixed by manually editing the info.plist file inside the bundle (screenshot below).

![image](https://user-images.githubusercontent.com/1724064/51642039-f4a9b080-1f35-11e9-9f78-55b2cc2eca2a.png)

**Comment by cristoslc** [comment]
Fixing this manually causes issues with codesigning for distribution via Test Flight. @nickorr any idea when you'll have a new signed build available?

**Comment by nickorr** [comment]
http://goya.com.au/files/beplugin/Test/BaseElements.fmplugin.zip

New public build of 4.0.5 coming soon too.

Cheers,
Nick
