### ISSUE TITLE
BE_PDFGetPages outputs a file with a size equal to the size of the input multiplied by the number of pages of the output (the same size or multiples larger than the original)

### ISSUE THREAD

**Issue by b-conk** [GoyaPtyLtd/BaseElements-Plugin#169]
When using BE_PDFGetPages to create a new PDF from a source PDF, the new PDF is the same file size as the source PDF, regardless of how few pages are in the new PDF.

**Comment by tohvanah** [comment]
I find it to actually be **much worse.** Every single page output is equal to the original file size! When outputting a single page, it is equal to the size of the entire original PDF. BUT, if you output 10 pages, it is the original size x 10. For example: an original PDF with 44 pages and 18MB in size, will result in a 180MB PDF output when selecting 10 pages!

The result of the function when a file path is provided for `newPDFPathOrContainer` is nothing, not "0". The result of the function when a field is provided for `newPDFPathOrContainer` is the actual PDF, and the field provided is not changed. 

When the `toPageNum` parameter is omitted, only one page is output, not the remainder of pages as described in the docs.
