### ISSUE TITLE
BE_SMTP_Send - not thread safe

### ISSUE THREAD

**Issue by dkiriakopoulos** [GoyaPtyLtd/BaseElements-Plugin#170]
Hi Nick,

Problem:
- 2 clients uses PSOS to send send attachments at the same time. Attachments gets overwritten.
- several clients use PSOS to send simple emails, one has an attachment: all emails are sent with attachments.

->Are there any future plans to make be_smtp_send _thread safe_ ?

Thank you very much!

**Comment by nickorr** [comment]
Denis,

The most recent 4.0.4 release is now thread safe :)

Cheers,
Nick

**Comment by dkiriakopoulos** [comment]
Great great news!!!
I think it's worth mentioning in the change-log! But anyway, thank you **very** much!!!

**Comment by tohvanah** [comment]
@nickorr BE_SMTP_Send is thread safe, or the whole plugin?! 🙏🏻

**Comment by nickorr** [comment]
Should be everything that is a supported server side plugin call.  Any testing that shows otherwise, let us know.

Cheers,
Nick
