### ISSUE TITLE
Some characters trigger auto-completion for BE_SetTextEncoding

### ISSUE THREAD

**Issue by nilswald** [GoyaPtyLtd/BaseElements-Plugin#171]
When you type one of the following characters into the data viewer, BE_SetTextEncoding is suggested: , - / '

![Bildschirmfoto 2019-03-23 um 08 27 27](https://user-images.githubusercontent.com/1010163/54863202-2082c000-4d46-11e9-80d1-1df48b0db755.png)

**Comment by nickorr** [comment]
Yep, we had a typo in that the description was being used as the suggested words.  Fixed in Dev and will be in the next release.

Cheers,
Nick
