### ISSUE TITLE
BE_RegularExpression: Freeze with incorrect syntax

### ISSUE THREAD

**Issue by hazi** [GoyaPtyLtd/BaseElements-Plugin#172]
FileMaker freezes on a formula in the process of writing.

For example
`BE_RegularExpression("TEST"; "()"; ""; "")`

Is this correctable?
I am particularly troubled if I have enabled Automatically evaluate in Data Viewer.

---
BaseElements 4.0.4
FileMaker Pro Advanced 17.0.4
macOS 10.14.4

**Comment by nickorr** [comment]
Thanks, there'll be a fix for this in 4.0.5.  If it's a bug like this, and not a compilation question, next time please post it at the main support site :

https://baseelementsplugin.zendesk.com/hc/en-us

Thanks,
Nick

**Comment by hazi** [comment]
I confirmed that the problem was solved in the test build.
Thank you.

http://goya.com.au/files/beplugin/Test/BaseElements.fmplugin.zip
