### ISSUE TITLE
Compatibility with FM 17 v5 ?

### ISSUE THREAD

**Issue by stevenadeau2** [GoyaPtyLtd/BaseElements-Plugin#173]
Title says it all.
Just updated to FMPA 17v5 and the BE plugin doesn't work anymore.
Rebooted, downloaded another copy just to make sure... same result.

I'll revert to using v4 until I hear otherwise.

(Mac OS 10.14.4)

**Comment by stevenadeau2** [comment]
Reinstalled FMPA 17v4, did not work.
Had to revert to 4.0.3 of BE plugin.

4.0.3 is 14.8 MB
4.0.4 is 11.4 MB

**Comment by JacobTaylor-RCC** [comment]
I can confirm that BE 4.0.2 also loads in FMPA 17v5.

**Comment by stevenadeau2** [comment]
I think it may have to do with 10.14.4 rather than FMPA 17v5: I did the update (from 10.14.3 to 10.14.4), but did not reboot my workstation until yesterday.

Now, I can't use my BaseElements 4 software because it wants to update the plugin when starting.

**Comment by factus10** [comment]
I'm at 17v4, OS 10.14.4. BE fails to initialize. I tried both installing in the folder and via the container/script (got a fail to initialize message)

**Comment by org** [comment]
Just noticed an issue too.  BE Plugin not initialised in FMP 17v4 / OS 10.14.4 - think was working fine but not sure when i last ran any code using the plugin

Maybe Apples Gatekeeper got a beef? or another certificate issue somewhere? I rolled back to BE 4.0.3 and seems ok for now (reboot FM to load rolled back Plugin)

**Comment by org** [comment]
> Just noticed an issue too. BE Plugin not initialised in FMP 17v4 / OS 10.14.4 - think was working fine but not sure when i last ran any code using the plugin

Just noticed release v4.0.5 which seems to fix my issue
https://github.com/GoyaPtyLtd/BaseElements-Plugin/releases/tag/4.0.5

**Comment by stevenadeau2** [comment]
4.0.5 solved the issue for me. Thank you for the quick response!

**Comment by factus10** [comment]
Now at 17v5, OS 10.14.4 and the latest BE download. Rebooted the computer. BE still fails to initialize. Put it in the extension folder under Applications, under Library and tried installing via the container/script. 

The only feedback I get is a fail to initialize message for the container/script method.

**Comment by factus10** [comment]
Ah, 4.0.5 fixed it for me, too. I was using the download link on the zendesk page. Explicitly downloading 4.0.5 did the trick.

**Comment by nickorr** [comment]
Which links are you referring to?  I've updated the main download links...

**Comment by factus10** [comment]
Mac version link on this page:  
https://baseelementsplugin.zendesk.com/hc/en-us/articles/360017562794-Downloads(https://baseelementsplugin.zendesk.com/hc/en-us/articles/360017562794-Downloads?mobile_site=true)

When did you update the link?

**Comment by nickorr** [comment]
I haven't changed it since Friday, but the link points to :

http://www.goya.com.au/files/beplugin/current/BaseElements.fmplugin.zip

and the "current" directory is an alias to 4.0.5 at the moment.

Cheers,
Nick

**Comment by factus10** [comment]
Strange, ok. Maybe Apple hates me.

**Comment by nickorr** [comment]
There's always that option.  I think you're ok though. :)

Cheers,
Nick
