### ISSUE TITLE
Quitting on mac

### ISSUE THREAD

**Issue by kdoronzio** [GoyaPtyLtd/BaseElements-Plugin#174]
The plugin seems to be causing two issues for me in FMPA17.0.6 / Mac 10.12.6 (Sierra) / BE 4.0.5, possibly related. 

1) When BE is the only plugin being loaded in FM, I always get the following error when I quit FileMaker. It's a normal quit, I intend to quit, but this message shows:
![image](https://user-images.githubusercontent.com/18170620/58490549-5cb61080-813b-11e9-999e-d42472cf0d37.png)

2) When both BE & 360Works SuperContainer Companion plugin are loaded, I can't quit FileMaker Pro. It just hangs indefinitely.

**Comment by nickorr** [comment]
Ken,

Submit a bug report here : https://baseelementsplugin.zendesk.com/hc/en-us and include a copy of the report from the "report..." button in the dialog.

Cheers,
Nick

**Comment by kdoronzio** [comment]
I don't see a place to submit a bug report there. I see feature request -
is that where I add it?

---------------------------------
Ken d'Oronzio
Paradise Partners, Inc.
866-999-4006 x201

**Comment by nickorr** [comment]
Yep, submit request button should be up the top.  Or email to support@baseelements.com will do it too.

Cheers,
Nick
