### ISSUE TITLE
handling MTOM MIME headers

### ISSUE THREAD

**Issue by dobunzli** [GoyaPtyLtd/BaseElements-Plugin#176]
Hello,
Using BE plugin I am able to obtain a SOAP response. Problem is that the server is using MTOM method to return the response (see example below).

Consequence is that the response contains MIME headers.
Filemaker Import XML datasource function is not able to import this kind of formatting. 

It would be nice if BE-Plugin could remove automatically those headers and keep only the xml text.
```
--MIMEBoundary_c444da12da6234c5f8931c4d746799b77da46cb1dde85cf4
Content-Type: application/xop+xml; charset=utf8; type="application/soap+xml"
Content-Transfer-Encoding: binary
Content-ID: <0.f444da12da6234c5f8931c4d746799b77da46cb1dde85cf4@apache.org>

<?xml version="1.0" encoding="utf8"?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Header></soapenv:Header><soapenv:Body><ns2:retrieveCodesResponse xmlns:ns2="http://service.interfaces.sense.at"><ns2:return xmlns:ns1="http://interfaces.sense.at/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns1:CodeResponse"><ns1:success>true</ns1:success><ns1:auditSources><ns1:codingScheme>senseAuditSources</ns1:codingScheme><ns1:displayName>Domain1</ns1:displayName><ns1:value>1.1.1</ns1:value></ns1:auditSources>
</soapenv:Body></soapenv:Envelope>
--MIMEBoundary_c444da12da6234c5f8931c4d746799b77da46cb1dde85cf4--
```

**Comment by nickorr** [comment]
Sorry, GitHub is for plugin compilation issues and questions.  There's a sponsor and support option for usage questions.

But as to MTOM, I'm not aware of any way to do this natively with the plugin, as it doesn't yet have the MIME and binary options.  This could be something we could add for a sponsor.

Cheers,
Nick
