### ISSUE TITLE
BE_GetSystemDrive causes FM to crash

### ISSUE THREAD

**Issue by PGMMattias** [GoyaPtyLtd/BaseElements-Plugin#177]
I tried the new function BE_GetSystemDrive in the Data viewer in FMP 18:

Process:               FileMaker Pro 18 Advanced [10677]
Path:                  /Applications/FileMaker Pro 18 Advanced/FileMaker Pro 18 Advanced.app/Contents/MacOS/FileMaker Pro 18 Advanced
Identifier:            com.filemaker.client.pro12
Version:               18.0.1 (18.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           FileMaker Pro 18 Advanced [10677]
User ID:               502

Date/Time:             2019-07-16 17:47:46.866 +0200
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Bridge OS Version:     3.0 (14Y901)
Anonymous UUID:        3223DF01-4C15-91F1-5D69-F5EB6637413C

Sleep/Wake UUID:       26B931BD-D296-4973-9FC2-9738C4A386A4

Time Awake Since Boot: 1200000 seconds
Time Since Wake:       22000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000692338b99bc0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [10677]

VM Regions Near 0x692338b99bc0:
    MALLOC_NANO (reserved) 0000600008000000-0000600020000000 [384.0M] rw-/rwx SM=NUL  reserved VM address space (unallocated)
--> 
    STACK GUARD            000070000c5cc000-000070000c5cd000 [    4K] ---/rwx SM=NUL  stack guard for thread 19

Application Specific Information:
Performing @selector(OnEvaluate:) from sender NSButton 0x600003130f20

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff6c46c56c objc_retain + 28
1   libobjc.A.dylib               	0x00007fff6c47196d objc_retainAutorelease + 9
2   au.com.goya.baseelements      	0x000000013712ad04 get_system_drive() + 164
3   au.com.goya.baseelements      	0x00000001371e24ff BE_GetSystemDrive(short, fmx::ExprEnv const&, fmx::DataVect const&, fmx::Data&) + 31

(I truncated the data dump here...)

**Comment by nickorr** [comment]
Yes, we're aware of this one, it only came up in the final build, and we're working on a fix.

Cheers,
Nick

**Comment by nickorr** [comment]
This one is also fixed in 4.1.3 :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmx64.zip

Cheers,
Nick
