### ISSUE TITLE
BE_ExecuteSystemCommand returns '?' with timeout of 0

### ISSUE THREAD

**Issue by jwillinghalpern** [GoyaPtyLtd/BaseElements-Plugin#180]
Hey Nick, I have a script that runs BE_ExecuteSystemCommand to run FMDataMigration ("data migration tool"). It used to work but no longer does. The command I'm running has not changed.

My calc is `BE_ExecuteSystemCommand ( $command ; 0 )`.

Mac OS Mojave
plugin version 4.0.5 works
plugin version 4.1.2 fails

The command actually runs fine when i set the timeout to 10000 or -1 (i.e. it doesn't timeout), but with a timeout of 0, BE_GetLastError returns 12000, and the function call returns '?'.

I'm using the timeout of 0 and piping stdout to a file so that i can have the filemaker script read in the file contents as they're being written, rather than after the command finishes.

I suspect the bug was introduced in plugin version 4.1: https://github.com/GoyaPtyLtd/BaseElements-Plugin/blob/fcdb8970be24c19f4eb21e8246afd44d16d81870/CHANGE_LOG#L49

**Comment by jwillinghalpern** [comment]
I just tested with plugin v4.1.1 and the bug is there too. 4.0.5 was the last version that worked for me. I have not tested on Windows.

**Comment by jwillinghalpern** [comment]
OK I did some more testing and I think the bug I'm concerned with is actually unrelated to the timeout param. I get that a timeout of 0 returns ? and be_error 12000 because technically the command "timed out". I will close this and open a more specific task for the real bug, which I think has to do with the re-write of BE_ExecuteSystemCommand and the way it parses the command.

**Comment by nickorr** [comment]
You beat me to it, yes the 12000 is expected for a 0 timeout, and it’s a change in behaviour.

GitHub is really for code ( c++ ) issues and issues relating to support for compiling etc.  If you need FileMaker support, there’s also the sponsor option on the website.

Cheers,
Nick

**Comment by jwillinghalpern** [comment]
Hey @nickorr thanks! Actually I think it's part of a deeper with the new c++ implementation of that function using Poco. I'm still formulating my thoughts about that, but the real issue I'm seeing is that stdout/err redirection no longer works and neither do multi-line commands. Where is the best place to post an issue like that?

**Comment by dansmith65** [comment]
I think the issue here is the documentation wasn't updated to reflect the changed code, it still says:

> Function calls that have a timeout of 0 will not return any values

Tests in **BaseElements Plugin Tests.fmp12** haven't been updated either.

**Comment by nickorr** [comment]
I’ve updated the docs to make it clearer about a 0 second timeout.

If you’ve got a really simple example that used to work, and now doesn’t please let me know.

Cheers,
Nick
