### ISSUE TITLE
Evaluating code with BE_EvaluateJavaScript crashes Filemaker

### ISSUE THREAD

**Issue by theelectricsoul** [GoyaPtyLtd/BaseElements-Plugin#182]
The following code always did its job well. But the following value crashes Filemaker. In a pure javascript enviroment the code runs just fine.

https://pastebin.com/DcXHBywh

**Enviroment**
Filemaker: 18.0.3.317 x64
BE: 4.1.2

**Comment by nickorr** [comment]
This works just fine for me on the Mac, on the same FileMaker versions.  If it's crashing on the Mac for you, send me a sample file and a crash log.

Any reason why you're not using the built in grep function for this?

Cheers,
Nick

**Comment by theelectricsoul** [comment]
1.
Well. We are using windows :) still want the dump ?

2.
We still haven't moved to x64, so I tested BE 32-bit first. 

3.
After scrolling through the change log, I switched to using the grep function in our side project. It does not crash. :)

**Comment by theelectricsoul** [comment]
System: Windows 10
BE: 4.1.2 x64

Just installed a fresh copy of FM 18 on a virtualBox. Fetched a copy of BE and copied it into the extension folder. Then started FM 18, opened the dataviewer without a fmp12 file.

It crashes immediately after pasting the code.

**Comment by nickorr** [comment]
Yes, if you're able to get a copy of the dump on windows ( not my area of expertise, so I don't know how easy it is to get ) that would be great.

A sample file that I can repeat this with would also be very helpful.

Thanks,
Nick
