### ISSUE TITLE
BE_FilemakerSql 4.1.2 returns unexpected results when columnDelimiter empty

### ISSUE THREAD

**Issue by theelectricsoul** [GoyaPtyLtd/BaseElements-Plugin#183]
We just switched from 32-bit to 64-bit. BE_FilemakerSQL changed its behaviour.

Replace {{anytable}} with a table of your choice. It must contain some testrecords :)

**BE_Version: 3.3.7**
`BE_FileMakerSQL ( "SELECT 3,1,2 FROM {{anytable}} "; ""; ¶ )`

**Returns**
`312
312
.....   etc`
**Result expected:** Yes( rows separated by carriage return)

---

**BE_Version: 4.1.2**
`BE_FileMakerSQL ( "SELECT 3,1,2 FROM {{anytable}} "; ""; ¶ )`

**Returns**
`3`
**Result expected:** No

**Comment by nickorr** [comment]
The plugin only sends the SQL to FileMaker to process.  Try doing the same with the executeSQL script step and you probably will get the same result.  you could also try submitting a bug report with FMI.

Cheers,
Nick

**Comment by theelectricsoul** [comment]
No problems with executeSQL

With executeSQL and leaving the columnDelimiter empty I get correct results with "FM 18" 32/64 bit. The only difference to BE is, that Filemaker includes a comma as delimiter when no delimiter is passed.
