### ISSUE TITLE
BE_FileListFolder fails with bullet character

### ISSUE THREAD

**Issue by doug-excelisys** [GoyaPtyLtd/BaseElements-Plugin#184]
BE_FileListFolder function returns "?" on Windows 10 when a filename contains the bullet character.

**Comment by nickorr** [comment]
Thanks, yes we're looking into this.

Cheers,
Nick

**Comment by nickorr** [comment]
Can you give me an example full path.  Does the BE Select Folder function return that path correctly?

Thanks,
Nick

**Comment by doug-excelisys** [comment]
The folder path isn't the problem. It's the names of the files within 
the folder. Here's an example:

     BE_FileListFolder ( "c:\test" )

When that folder contains only a file name "test.txt", the function call 
works fine. Putting a second file in that folder named "test•2.txt" 
causes the function call to return "?".

**Comment by nickorr** [comment]
Great, thanks.

**Comment by nickorr** [comment]
Doug,

New builds that have a fix for this.  Love it if you could test :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmx64.zip

Thanks,
Nick

**Comment by davidhamann** [comment]
Had a similar issue with umlauts in filenames on Windows 10, leading to "?", or error 0x2, respectively.

The new builds solve that issue as well. Thanks!

**Comment by nickorr** [comment]
Thanks David.
