### ISSUE TITLE
BE_FileMakerSQL Only Taking 1 character as delimiter?

### ISSUE THREAD

**Issue by LondonWillGeorge** [GoyaPtyLtd/BaseElements-Plugin#185]
Hi, I'm not sure if this is an 'issue' for the plugin code, or if I somehow changed a FileMaker or Windows setting without realising but this line of FileMaker script worked less than a week ago, but doesn't work since yesterday:

`BE_FileMakerSQL ( $sql_select;  "<c>" ; "<r>" ; $fm_file )
`
This is now putting '<' as delimiter between the fields in the output from a SQL Select statement saved in the variable $sql_select, ie looks like it is only reading the first character of delimiter string. It should be putting '\<c>' as field delimiter, and indeed was a few days ago. Any ideas what could be wrong? Thanks so much for any suggestions!

**Comment by LondonWillGeorge** [comment]
OK sorry not much of an issue anyway, as I can use very obscure 1 character delimiter in FileMaker instead, I used a very complex Chinese character. But I'm still confused why this seemed to happen.. I see docs say this command can only use 1 character delimiter, but I'm sure I was using '<c>' and '<r>' successfully before.

**Comment by nickorr** [comment]
Obviously nothing in the plugin changed remotely in the last week, so I'm not sure how to explain the change.  If you've got a new version of BE or FMP, then that would make a difference...

Old versions of the SQL api let you do this, no idea why the new one doesn't.  Best bet would be to submit a bug report with FileMaker.

Cheers,
Nick

**Comment by LondonWillGeorge** [comment]
Thanks kindly @nickorr I will submit with FileMaker
