### ISSUE TITLE
Base Elements plug-in not loading anymore since this morning

### ISSUE THREAD

**Issue by PeterWagemans** [GoyaPtyLtd/BaseElements-Plugin#186]
We did a short analysis at the customer, and it seems only machines before Catalina are affected.
Machines that ran through the night see the plug-in. When we simply stop and start FileMaker again on these pre-Catalina machines, they do not load the plug-in anymore.

Some certificate expired in the plug-in?

**Comment by jwillinghalpern** [comment]
This just happened to me suddenly not 10 minutes ago

**Comment by PeterWagemans** [comment]
No dates to see in the codesigning:

Identifier=au.com.goya.baseelements
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=94904 flags=0x0(none) hashes=2960+3 location=embedded
VersionPlatform=1
VersionMin=658688
VersionSDK=658944
Hash type=sha256 size=32
CandidateCDHash sha256=04d73234f0b10d6632f120605e0f899a38bf2595
CandidateCDHashFull sha256=04d73234f0b10d6632f120605e0f899a38bf25959ea3bcfb2e3222ccf805168a
Hash choices=sha256
CMSDigest=04d73234f0b10d6632f120605e0f899a38bf25959ea3bcfb2e3222ccf805168a
CMSDigestType=2
Page size=4096
CDHash=04d73234f0b10d6632f120605e0f899a38bf2595
Signature size=4693
Authority=Mac Developer: Mark Banks (28M488SVWV)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=7 Aug 2019 at 10:07:00
Info.plist entries=19
TeamIdentifier=GUZF844KMZ
Sealed Resources version=2 rules=13 files=2
Internal requirements count=1 size=180

**Comment by PeterWagemans** [comment]
It works again if I sign it myself.

**Comment by tom1200** [comment]
Same issue here. I reinstalled 4.0.5 version witch works.

**Comment by nickorr** [comment]
Do the FileMaker logs or the console show anything else about why it happened?

**Comment by PeterWagemans** [comment]
No couldn't find anything. But I am not that handy with the console.

**Comment by nickorr** [comment]
The console is a disaster, but the search works.  Try searching for BaseElements shortly after starting FileMaker.  That should get you some answers.

**Comment by PeterWagemans** [comment]
Nick, I already got answers. The code signing is broken on older macOS versions. Surely it is somewhere there, but the answer is simple. re-codesigning does the trick.

**Comment by nickorr** [comment]
I've uploaded a build with a new codesign, can you test :

http://goya.com.au/files/beplugin/4.1.2/BaseElements.fmplugin.zip

( I don't have an easy access pre-catalina build to try on... )

Thanks.

**Comment by PeterWagemans** [comment]
I'll transfer this to a pre-Catalina machine and will let you know in a few minutes.

**Comment by PeterWagemans** [comment]
Yup. That works.

**Comment by nickorr** [comment]
Awesome, thanks for your help. I'll have a play with the other releases in the morning and see if I can figure out what it was.

Cheers,
Nick

**Comment by PeterWagemans** [comment]
Yes, it's kinda weird. Cheers! -- peter

**Comment by petrowsky** [comment]
Just chiming in here. My default system is still Mojave 10.14.6(18G4032) The hosted version from https://baseelementsplugin.zendesk.com of 4.1.2 dated Aug, 7 2019 is, in fact, not loading. Using your re-signed copy in the comment above does in fact load.

Searching the Console log for anything 'BaseElements' does not reveal any info when searching All Messages.

**Comment by petrowsky** [comment]
@nickorr I can tweet out an announce via my magazine account if you want people to know in order to potentially reduce support requests.

**Comment by nickorr** [comment]
Matt,

Thanks for those details.  It's morning here, so I've had a few support requests :)

But if you don't mind tweeting something, every little bit helps.

I'll do a blog post today once I've figured it all out.

Cheers,
Nick

**Comment by petrowsky** [comment]
Posted a tweet and referenced your @baseelements Twitter account for updates.

**Comment by mr-scott** [comment]
That download fixed it for my systems. Thx

**Comment by dzakary** [comment]
I had the same problem on my High Sierra FMS system. The fix (thanks to Wim Decorte for reminding me to do this) was create a file with the plugin, host it, open in client and do a PSoS that installs the plugin. I think I may have also had some permission issues on the plugin folder on the Server machine.

**Comment by mr-scott** [comment]
Are there plans to release a new version higher than 4.1.2? The reason I ask is that I have a "Plugins" file that is incorporated into startup scripts to automatically keep clients up-to-date — so they don't (or, I don't) have to waste time doing it on a per-user manual basis. 4.1.21 would be fine.

**Comment by nickorr** [comment]
mr-scott,

If you've got a version that's not loading, but have the new 4.1.2 in a container, the new one will install over the top of the one that's not working.  So version numbers shouldn't matter.

But we will do a new release soon too.

Cheers,
Nick

**Comment by mr-scott** [comment]
Hi, Nick:

Unfortunately, I do a version check at startup, so it does matter for my solutions. Just any increment higher will do. Thanks for the response.

**Comment by nickorr** [comment]
Yes, but if the plugin isn't installing, the version check will be ? which means it's not installed.  So you'll be able to install the new one, regardless of the fact that the other one is the same version.

You can't tell what version an uninstalled plugin is, so it doesn't matter that it's the same.

Cheers,
Nick

**Comment by mr-scott** [comment]
OK…Good point.

**Comment by jdfletchr** [comment]
Thanks, Nick. Looks like that does the trick! (Working in Mojave and Catalina.)

**Comment by tom1200** [comment]
Hi,
Today, the Filemaker Server BaseElement plugin no longer worked, due to the same problem.
I do not know why it happened so late, maybe Filemaker Server reloaded the plugin.

**Comment by tteuer** [comment]
I'm having the same issue in Mac OS Catalina. “BaseElements.fmplugin” can’t be opened because Apple cannot check it for malicious software." Was working until the past couple of weeks it seems.

**Comment by nickorr** [comment]
I've uploaded a build with a new code signature  :

http://goya.com.au/files/beplugin/4.1.2/BaseElements.fmplugin.zip

Cheers,
Nick

**Comment by nickorr** [comment]
Also got a 4.1.3 build which seems to be working fine :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip

Cheers,
Nick

**Comment by tteuer** [comment]
Thank you Nick! 4.1.3 seems to be working nicely on both of my Catalina installs
