### ISSUE TITLE
Plugin doest not load with Filemaker 19

### ISSUE THREAD

**Issue by tom1200** [GoyaPtyLtd/BaseElements-Plugin#189]
Hi,
This issue is related to the previous one which has been closed.

When opening the plugin in Filemaker 19 in Catalina Os, a system message indicates : “BaseElements.fmplugin” can’t be opened because Apple cannot check it for malicious software."

It happens the new build 4.1.2 from http://goya.com.au/files/beplugin/4.1.2/BaseElements.fmplugin.zip which load well with Filemaker 18.

Furthermore, the loading can't be forced in System Preferences : the button Open Anyway has no effect.

**Comment by tom1200** [comment]
In addition : if I move the BaseElement Plugin installed in Filemaker 18 (which has been approuved by the system) in Filemaker 19 extension, Filemaker 19 loads it without error.

**Comment by nickorr** [comment]
Tom,

You've got an old version of the plugin somewhere in a folder that FileMaker is trying to load.  Delete all the old copies of the plugin first.

Cheers,
Nick

**Comment by tom1200** [comment]
Hi Nick, thank you for your response.

It'a new computer and the only old copy of the plugin was the one you provided in the other issue thread (http://goya.com.au/files/beplugin/4.1.2/BaseElements.fmplugin.zip). I downloaded it two weeks ago.

This copy of the plugin, **and it's copies if I duplicate it**, works fine with Filemaker 18 and Filemaker 19.

But if I download again the plugin, this version do not work with Filemaker 18 and 19.  Mac Os detects that it is a new file and refuse to validate it.

**Comment by nickorr** [comment]
Thanks for the detail.  Weird things are happening with this, if I copy the one out of the v18 folder, it works.  Zip that one, upload it to the website, download it, it doesn't work. :(

Try this one :

https://goya.com.au/files/beplugin/4.1.3/BaseElements.fmplugin.zip

Cheers,
Nick

**Comment by tom1200** [comment]
Hi Nick,
The 4.1.3 version works on Filemaker 18 and 19.

**Comment by nickorr** [comment]
Awesome, great to hear.

Cheers,
Nick
