### ISSUE TITLE
Curl Version Update

### ISSUE THREAD

**Issue by andy-tsg** [GoyaPtyLtd/BaseElements-Plugin#193]
Any chance you could bump the curl version to a newer/newest version?

**Comment by nickorr** [comment]
Andy, just thought I'd ping in here.  We're always adding updates into builds, unless there's specific features that we might try to take advantage of.

Sponsors get access to new builds automatically via dropbox too.  So if there's ever a feature in a new build of curl ( like there's the new AWS stuff in the latest ones ), let us know.
