### ISSUE TITLE
SMTP Bare Line Feeds Rejected

### ISSUE THREAD

**Issue by trevorgildersleeve** [GoyaPtyLtd/BaseElements-Plugin#195]
I have a client who has been sending SMTP emails via the plugin for years without issue. Last week they switched to Office 365 mail, and I was able to get the plugin to send through smtp.office365.com.

However, now the users are getting undeliverable messages complaining about Bare Line Feeds. Is this something that I need to change in my FileMaker templates, or something the plugin should either be handling or not introducing?

They are currently using version 4.1.4 on Windows.

Thank you - Trevor Gildersleeve

![2021-05-05_09-47-37](https://user-images.githubusercontent.com/17937538/117152009-9d871d00-ad87-11eb-8c8e-14a36a368cd4.png)

**Comment by nickorr** [comment]
Trevor,

Thanks, this is an issue that has been reported before.  I have a hunch about what it might be, can you please try testing with 3.3.6 :

https://goya.com.au/files/beplugin/3.3.6/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/3.3.6/BaseElements.fmx64.zip

Thanks,
Nick

**Comment by trevorgildersleeve** [comment]
Thanks Nick,

I loaded 3.3.6 on a Windows machine and resent the message (which does have a PDF attachment), and it also bounced.
I will likely need to get you a test file that replicates the issue, but you would need a 365 email account to send from.
If the SMTP curlTrace helps, I can send you that privately.

**Comment by nickorr** [comment]
Trevor,

No it appears to be unrelated.  I have had other clients with this issue, and in those cases it appears to be related to the mail server - using a different sending server fixed the issue.

I can't explain why it happens on some servers and not others, or only with the plugin and not other methods.

I've seen lots of people connect to office 365 and not have this issue though?  Are you sending via office365?  Does it go to some users and not others?

Cheers,
Nick

**Comment by trevorgildersleeve** [comment]
Sorry for the late response on this. I had to move on and switch to a different plug-in for sending mail which is working now.

**Comment by nickorr** [comment]
Trevor,

Any chance I could get you to test a new build?  I think we've found something that may have been the cause of the issue.

https://goya.com.au/files/beplugin/Test/BaseElements.fmplugin.zip

Thanks,
Nick

**Comment by trevorgildersleeve** [comment]
Thanks for continuing to investigate this. I just tried it with the new build and unfortunately I received the same result. I forward you some additional details that I'm not comfortable putting here since it has my client info/details in it.
