### ISSUE TITLE
Unable to install baseelements plugin on Mac M1 and client 19.3

### ISSUE THREAD

**Issue by danilolutti** [GoyaPtyLtd/BaseElements-Plugin#199]
Unable to install baseelements plugin on Mac M1 and client 19.3

Error 1550.

**Comment by bigdamidea** [comment]
Same issue here - can't activate on the admin console, toggle goes off immediately again. 19.3 on Big Sur 11.4

**Comment by danilolutti** [comment]
on the client I solved using rosetta on FM Pro launch.

**Comment by LeJeko** [comment]
> Same issue here - can't activate on the admin console, toggle goes off immediately again. 19.3 on Big Sur 11.4

Same issue with Ubuntu 18.04 LTS who is needed for FMS 19.3.1.
_Error 747 : Plug-in failed to load : BaseElements.fmx_

**Comment by nickorr** [comment]
All : M1 is a completely new platform, it requires both FMP and the plugin to be rebuilt for the new platform to run natively.  There's a new M1 and ubuntu version available here :

[https://goya.com.au/blog/baseelements-plugin-for-m1-and-ubuntu](https://goya.com.au/blog/baseelements-plugin-for-m1-and-ubuntu)

Only 4.2 and later will run on either ubuntu or M1 native.

Let us know if you come across anything that doesn't work, or behaves differently.

Thanks,
Nick
