### ISSUE TITLE
Version 4.2.0 will not load

### ISSUE THREAD

**Issue by Hubert-62** [GoyaPtyLtd/BaseElements-Plugin#203]
Version 4.2.0 does not load under MacOs 10.13.6 and FileMaker 17.0.7.700. Are there system limits here?

**Comment by nickorr** [comment]
Yes, we'd added in some functionality that was v18 only.  We hadn't documented this, so we'll do an update to revert that and push it back to the 5.x branch instead.

So 4.2.1 should re-enable v17.

**Comment by Hubert-62** [comment]
Thank you very much for your reply. When can we expect version 4.2.1?

**Comment by nickorr** [comment]
Give this one a try :

https://goya.com.au/files/beplugin/Latest/BaseElements.fmplugin.zip
https://goya.com.au/files/beplugin/Latest/BaseElements.fmx64.zip

Cheers,
Nick

**Comment by Hubert-62** [comment]
Thank you very much for the link. The PlugIn is now recognized and loaded again by FileMaker 17 and even FileMaker 16.
Thank you and best regards,
Hubert

**Comment by nickorr** [comment]
4.2.1 is now final and released :

https://docs.baseelementsplugin.com/article/522-downloads
