### ISSUE TITLE
BE_ExecuteSystemCommand error -1

### ISSUE THREAD

**Issue by danilolutti** [GoyaPtyLtd/BaseElements-Plugin#204]
I have an issue with the BE_ExecuteSystemCommand command.
Sometimes it stops working and the result is ? (-1 error with BE get last error).
Rebooting filemaker server will resolve the issue and BE_ExecuteSystemCommand works again.

the system command is a simple .bat with 2 rows:
@CD ..
@curl -X POST..

sever plugin version: 4.2.2
fms version: 19.3.2.203
platform: Windows Server 
Windows curl version: 7.62

when the plugin is "down" if i double click the .bat script, the command will works, 
but when running the same command with the plugin I get a -1 (curl?) error.

after windows reboot, it works again.

**Comment by nickorr** [comment]
Danilo,

The best place to get support is at https://docs.baseelementsplugin.com.

When this happens, and the command returns ?, can you try two things : 

Run a very basic command such as "dir" and tell me what it returns and the result of the BE Error function.
Run the BE debug function as well.

When you say you get a -1 error, is that from the BE_ExecuteSystemCommand function or from the BE Error function?

Cheers,
Nick

**Comment by danilolutti** [comment]
> When you say you get a -1 error, is that from the BE_ExecuteSystemCommand function or from the BE Error function?

- set variable $cmd -> BE_ExecuteSystemCommand ( path/myCommand.bat ) 
- $cmd = "?"
- ser variable $lastError -> BE_GetLastError
- $lastError = "-1"

after reboot filemaker server machine
- set variable $cmd -> BE_ExecuteSystemCommand ( path/myCommand.bat )  -> it works.


> Run the BE debug function as well.

I will add BE_DebugInformation as well, so the next time I'll get the debug info.
thanx.

**Comment by nickorr** [comment]
Send me the entire path/command, it's hard to help when I don't know what you're actually doing.

**Comment by LeJeko** [comment]
> I have an issue with the BE_ExecuteSystemCommand command. Sometimes it stops working and the result is ? (-1 error with BE get last error). Rebooting filemaker server will resolve the issue and BE_ExecuteSystemCommand works again.
> 
> the system command is a simple .bat with 2 rows: @cd .. @curl -X POST..
> 
> sever plugin version: 4.2.2 fms version: 19.3.2.203 platform: Windows Server Windows curl version: 7.62
> 
> when the plugin is "down" if i double click the .bat script, the command will works, but when running the same command with the plugin I get a -1 (curl?) error.
> 
> after windows reboot, it works again.

Hi,

Same issue here after upgrading from FMS 18.0.4/macOS 10.15.7/BE 4.1.4 to FMS 19.4.2/macOS 12.1/BE 4.2.2.
The BE_ExecuteCommand do not work with result ? and error -1. No more informations in Debug.

Works fine again with BE 4.1.4.

**Comment by nickorr** [comment]
Do you have any idea of how many times you're calling the BE function before it fails?

Where is the .bat file and what's the full path?  Is it doing something outside of the root FMS docs folder.

What do you mean "no more informations in debug", can you send me the debug result?

After it starts to fail, if you run a very simple BE execute, like "dir" does that work, or do all commands then fail?

**Comment by nickorr** [comment]
There's also a 4.2.3 out now, but I'm not sure it has any changes for this, but worth testing with.

**Comment by nickorr** [comment]
Danilo,

There's a 4.2.4 which also fixes an issue on windows where the command sent to BE_ExecuteSystemCommand would complete before the plugin could start to wait for the result.

https://goya.com.au/files/beplugin/4.2.4/BaseElements.fmx64.zip
