### ISSUE TITLE
BE_Version reports 4.2.2 for latest release (4.2.3)

### ISSUE THREAD

**Issue by davegraham92120** [GoyaPtyLtd/BaseElements-Plugin#207]
The BE_Version function reports 4.2.2 for the latest version of the plug-in on macOS, which is 4.2.3. I haven't tested it on other platforms. 

FileMaker Pro version 19.4.2.204
macOS version 12.0.1 (21A559)

![image](https://user-images.githubusercontent.com/20668953/151238967-5fcaf107-9704-445f-897e-24b109b0d574.png)

**Comment by davegraham92120** [comment]
Hmmm... it looks like the version number still shows the old version after installing a new one via script step. After I quit and reopened FileMaker it's now showing the correct version.

**Comment by nickorr** [comment]
Yep, that's a FileMaker bug.  It reports 0 error when doing the install, but the old plugin is still loaded.  I've got a bug report here :

https://community.claris.com/en/s/question/0D53w000059nwXYCAY/plugins-dont-update-depending-on-location

It doesn't seem to be on their radar, so any additional bug reports you could add would be very much appreciated.

Cheers,
Nick
