### ISSUE TITLE
BE_ExecuteSystemCommand returns Access is denied error

### ISSUE THREAD

**Issue by jlgill** [GoyaPtyLtd/BaseElements-Plugin#208]
Hello,

I'm attempting to use the AWS CLI to extract a list of suppressed email addresses, save them to a local file, and then import the data into FileMaker.  When writing the data to a local file BE_ExecuteSystemCommand returns a message stating 'Access is denied' and BE_GetLastError returns false.

OS: Windows 10 (Build 19044.1526)
BE Version: 4.2.3

Command: BE_ExecuteSystemCommand ( "echo This is a test > test.txt" ; 5000 ) & "¶" & BE_GetLastError 
Result: Access is denied.
0

**Comment by nickorr** [comment]
Access Denied means exactly that : your command line session doesn't have permissions to do what you're asking, in this case write to the folder you've specified.  Do a search for "Access is denied" with windows cmd, there's lots of examples, and this isn't related to the plugin specifically.
