### ISSUE TITLE
Base Elements plug-in not loading anymore since this morning ( 3.3.8 )

### ISSUE THREAD

**Issue by bmcprocess** [GoyaPtyLtd/BaseElements-Plugin#209]
The Windows 32 bit Version (https://goya.com.au/files/beplugin/3.3.8/BaseElements.fmx.zip) ( 3.3.8 ) stopped loading this morning at 00:00:00 UTC.

I not a similar issue (https://github.com/GoyaPtyLtd/BaseElements-Plugin/issues/186) two years ago.

Has the code signing expired again?

**Comment by nickorr** [comment]
​Yes, it seems that the signing certificate has an expiry date, which was the 5th April.  I had believed that you could continue to run software that was outside it's signed window, as long as you first ran it once within the window.  Perhaps something to do with FileMaker and plugins means that process doesn't work.
​
​I've started the process to get a new windows signing certificate, but believe it or not, it takes 2-3 days for them to verify me.  :(  I'll let you know as soon as that's done, and I have a new version I can sign and send out.

**Comment by nickorr** [comment]
New re-signed builds :

https://goya.com.au/files/beplugin/3.3.8/BaseElements.fmx.zip
https://goya.com.au/files/beplugin/3.3.8/BaseElements.fmx64.zip

Cheers,
Nick

**Comment by bmcprocess** [comment]
Thank you.

Stephe
