### ISSUE TITLE
BE_Zip does not error on multiple files with same name reliably

### ISSUE THREAD

**Issue by tomaptx** [GoyaPtyLtd/BaseElements-Plugin#213]
BE_Zip (4.2.4) actually zipped the first 3 files of a 40 file list where there were duplicates of every filename in the list. I would expect this to throw the error immediately on the first occurrence of a duplicate.

**Comment by nickorr** [comment]
Can you submit support requests here : https://docs.baseelementsplugin.com

And please include all the detail of the plugin function calls, including parameters, responses, and result of the BE Error and Debug functions.

Thanks,
Nick
