### ISSUE TITLE
BE_HTTP_POST crashes script engine with FileMaker Server 2023 on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by iAlchemy** [GoyaPtyLtd/BaseElements-Plugin#217]
We're using version 4.2.6 on FileMaker Server 2023 on Ubuntu 20.04.6 and recently built a new FileMaker Server 2023 on Ubuntu 22.04.2.  Scripts called with Perform Script on Server that were previously working are now causing the script engine to crash when we call the BE_HTTP_POST function.  Tested with the minimum required parameters and verified the same script works successfully when run from FileMaker Pro.

Are there known issues with BaseElements-Plugin and Ubuntu 22.04.2?

**Comment by nickorr** [comment]
I'm aware of an issue with SMTP and the plugin on ubuntu 22, but not 20.  Can you confirm exactly the step that is causing the issues, and let me know what specifically you're using to call the plugin function.  

Please use the contact form here : https://docs.baseelementsplugin.com/ and leave git for code compiling issues.

Thanks,
Nick

**Comment by iAlchemy** [comment]
Hi Nick,You’ve closed the issue. Does that mean it’s not actually an issue, you’ve resolved it, or still need more info?Basically all was good under Ubuntu 20.04 with the latest version of FileMaker Server 2023. I needed to deploy a new server for a client who was running CentOS on bare metal and chose to go with a Ubuntu 22.04 VM on Proxmox.  It all looked good but I neglected to validate the SMS component.  In hindsight I should have refactored that section ages ago to not use the BaseElements Plug-in to do a HTTP POST but as I t wasn’t broken I hadn’t fixed it. I’m now using Insert from URL with appropriate CURL options so I’ve resolved my issue, however I thought I’d raise the issue none the less as I noted that there was an issue with the SMTP function. Cheers, MalcolmSent from my iPhoneOn 1 Aug 2023, at 11:06 am, Nicholas Orr ***@***.***> wrote:﻿
I'm aware of an issue with SMTP and the plugin on ubuntu 22, but not 20.  Can you confirm exactly the step that is causing the issues, and let me know what specifically you're using to call the plugin function.
Please use the contact form here : https://docs.baseelementsplugin.com/ and leave git for code compiling issues.
Thanks,
Nick

**Comment by nickorr** [comment]
It's just closed because this isn't the place for plugin support, like I mentioned, please use the contact form at https://docs.baseelementsplugin.com/ for support.

But also I need more info from you, specifically that you've confirmed specifically that it was the HTTP POST and not some other call in the same script and I need all the specifics of that call to help.

Please send all that to the support contact form.
