### ISSUE TITLE
5.0.0 Final Be_SQL UPDATE changes accented characters

### ISSUE THREAD

**Issue by glitchtracker** [GoyaPtyLtd/BaseElements-Plugin#220]
Hi,
Found another bug in 5.0b3 and 5.0.0 Final , same build has previous reports from me, I think its the latest.

UPDATE update_problem SET data='Accents : àèéîôû' WHERE id=1

actually writes

Accents : √†√®√©√Æ√¥√ª

No problems with 4.2.6

My file was created on a french mac os
Ventura, M1 Mac

file plus video here
https://mega.nz/file/sIJlxbIL#KqkKWMapFeMDJnCcWyoYv9tMQNZVtQe89Ir2_o7s93Y

**Comment by nickorr** [comment]
Dupe for #125

**Comment by glitchtracker** [comment]
Duep of #125, are you sure #125 talks about BE_ExecuteSystemCommand ?, I'm talking Be_SQL
