### ISSUE TITLE
Enable ARM64 support on Ubuntu 22.04

### ISSUE THREAD

**Issue by alexandrosraikos** [GoyaPtyLtd/BaseElements-Plugin#221]
As FileMaker 2023 now natively supports ARM64 on Ubuntu Linux, we have begun migrating our resources to ARM64 servers for increased efficiency. We are aware of the conversation on #216 regarding ARM support, and  we are opening this issue to inquire on this implementation's progress and add another eager voice to the choir.

**Comment by nickorr** [comment]
If you have anyone with linux c compiler experience, then we've got a set of compile instructions in this repo : https://github.com/GoyaPtyLtd/BaseElements-Plugin-Libraries

The entire set of library files need to be recompiled before we then can re-do the BE plugin compile and then test.

**Comment by nickorr** [comment]
Closing this as there is already an issue open for this.

**Comment by nickorr** [comment]
Can you test out the new version 5.1.0b3 ( 5.1.0.6 ) and report any issues here : 

https://github.com/GoyaPtyLtd/BaseElements-Plugin/blob/main/docs/Downloads.md
