### ISSUE TITLE
Base Element not loading on FMS 19.6.3.302

### ISSUE THREAD

**Issue by yorleumas** [GoyaPtyLtd/BaseElements-Plugin#222]
We have an FMS server on windows 2016 server. The Plugin on the console is enabled. Other plugins work very well but the baseelement plugin does not work. If I activate/deactivate the plugin, nothing is written in the event log. I tried version 5 and 4.2. I use the install plug in file on server function. When I use the functions on the server I always get ? as a result.

**Comment by nickorr** [comment]
I recommend you install via scripting using a container field and the install plugin script step.  See these docs :

https://docs.baseelementsplugin.com/article/558-how-to-install-the-baseelements-plugin

You can use that site for support requests.
