### ISSUE TITLE
FTP Upload stopped working after server upgrade

### ISSUE THREAD

**Issue by rpoelking** [GoyaPtyLtd/BaseElements-Plugin#231]
**Describe the bug**
FTP upload returns error 2 after upgrading from Ubuntu 20/FMS 20 to Ubuntu 22/FMS 21

**To Reproduce**
We need to know :
1. BE_FTP_Upload, BE_FTP_UploadFile, BE_CurlTrace, BE_DebugInformation
2. BE_FTP_Upload ( 
$baseURL & $folder & GetContainerAttribute ( Dashboard::CONTAINER ; "filename" ) ; 
Dashboard::CONTAINER ; 
CryptDecryptBase64 ( $un ; $cryptKey ) ; 
CryptDecryptBase64 ( $pw ; $cryptKey ) )
3. "?" Error 2
4. BE_CurlTrace returned a "?" and BE_DebugInformation causes the script to fail

**Expected behavior**
FTP upload success

**Desktop (please complete the following information):**
 - OS and version : Ubuntu 22
 - FileMaker Version FMS 21
 - Plugin Version from BE_VersionAutoUpdate 04020600

**Additional context**

 - CurlTrace failed to report anything
 BE_DebugInformation Causes script to crash

5 minute Loom Video demonstrating: https://www.loom.com/share/93ce09dc7905468e82fa2cbccee4c210?sid=96d1214f-eb33-4696-91b7-dec75fadd08c

**Comment by nickorr** [comment]
Rob, Error 2 is "The URL was not properly formatted". https://curl.se/libcurl/c/libcurl-errors.html

What was the actual url?

**Comment by rpoelking** [comment]
<img width="704" alt="Screenshot 2024-10-17 at 07 15 41" src="https://github.com/user-attachments/assets/e2514e79-1925-4ca6-87f1-a1b9fccebf76">
I had to obfuscate part of it, but as I mentioned earlier, this has been rock solid for years. I don't seen anything wrong with the URL.

**Comment by rpoelking** [comment]
@nickorr I sent you a sponsorship. If you don't mind taking a look into this, please.

**Comment by nickorr** [comment]
Thanks, can you put the steps with the actual paths into a script in a new FileMaker file, and email it to me direct : nick@goya.com.au

I need to see the details of folders and parameters etc.

**Comment by rpoelking** [comment]
Nick,
V5! That did it!
It's working like it used to. Thank you for your help. 

Rob

**Comment by nickorr** [comment]
I'm still resolving some library compiling issues on v5, but for reference this is the most recent 5.0 build : 

https://goya.com.au/files/beplugin/5.0.0/BaseElements_ubuntu22.fmx.zip
https://goya.com.au/files/beplugin/5.0.0/BaseElements_ubuntu20.fmx.zip
