### ISSUE TITLE
WPE won't start after installing the version 5.0 of the plugin in the WPE-plugins folder

### ISSUE THREAD

**Issue by MaxbizSolutions** [GoyaPtyLtd/BaseElements-Plugin#233]
**Describe the bug**
WPE won't start after installing 
version 5.0.0.2 of the plugin in the WPE-plugins folder.

After removing the plugin from the WPE-Plugins folder, FMS asks to install Java everytime that the WPE is started. 
The Java folder is not deleted or moved, but is overwritten by the upload of OpenJDK17U-jdk_x64_windows_hotspot_17.0.13_11.zip

The WPE then starts and works. However, the Connectors GUI is missing the option to replace the JDK and the JDK version.
Replace JDK  
JDK Version
![Screenshot 2024-12-11 at 6 43 58 PM](https://github.com/user-attachments/assets/980c3a16-9ecc-4423-bb77-8c83413e9bf3)

**To Reproduce**
Put the plugin into the WPE plugins folder. Start the WPE.
C:\Program Files\FileMaker\FileMaker Server\Web Publishing\publishing-engine\cwpc\Plugins\

**Expected behavior**
The WPE should start.

**Server (please complete the following information):**
Windows Server 2019 DataCenter in a Virtual Machine in a hosting environment.
FileMaker Server 21.1.40
"version" : "5.0.0.2"

**Additional context**
The plugin installed in the server extensions folder seems to be working at this time when it is called from the PSOS process.

**Comment by nickorr** [comment]
I'm not 100% clear what the issue is here.  Without the plugin installed, does all of the FMS functionality work as expected?  

I can't see any possible interaction between the plugin and the JDK, so not sure what the connection is there.

Given you're saying it works in the fmse, can you just use scripts there for plugin actions ( so call via PSOS from wpe ) to workaround it temporarily?

**Comment by MaxbizSolutions** [comment]
It is working with FMSE for the functions we use.
I did not consider using WPE to call a PSOS. I wll look into that process.

The issue is that it seems to have somehow corrupted the WPE so that it won't stop and start correctly now. 
I may have re-install of FMS to try and fix it.
I just wanted others to know to not install it in the WPE plugins folder and then have the same problems.
Thanks for your response.

**Comment by nickorr** [comment]
It's unlikely to be that a plugin can corrupt the WPE, and anything the plugin does is resolvable by removing the plugin.

I'd guess there's another issue there, but hard to diagnose remotely.
