### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by jpscharf** [GoyaPtyLtd/BaseElements-Plugin#42]
Have you thought about or planned on adding a regular expression function?

**Comment by nickorr** [comment]
Jason,

We've started adding a JavaScript evaluate option to the plugin, : http://www.goya.com.au/blog/baseelements-plugin-31-beta-available-now-includes-smtp

Cheers,
Nick

**Comment by jpscharf** [comment]
Nick,

It is awesome you are adding js to the plugin. Is there any docs on how to use the hidden function?

Thank You,
––
Jason P. Scharf
FileMaker Certified Developer (11-13)
Apple Certified Support Professional
iNtergrated LLC, "Designing the Future Today!"
812.989.6267
jason.scharf@intergrated.net
http://www.intergrated.net

**Comment by nickorr** [comment]
Yep, I'm moving all the docs to this site : https://baseelementsplugin.zendesk.com/hc/en-us/articles/204528287-BE-EvaluateJavaScript <https://baseelementsplugin.zendesk.com/hc/en-us/articles/204528287-BE-EvaluateJavaScript>

So far it's only the new or changed in 3.1 functions.  You do need a ( paid ) sponsorship account to login or post questions though.

Cheers,
Nick
