### ISSUE TITLE
feature request: unzip to container

### ISSUE THREAD

**Issue by dansmith65** [GoyaPtyLtd/BaseElements-Plugin#72]
Is it possible to either modify BE_Unzip, or provide a new function that can send the output directly to a container field? While you're at it, it would be nice to optionally be able to have the input come directly from a container field.

The use-case is for downloading a compressed Mac plugin on a Windows computer, uncompressing the downloaded file and saving the .fmplugin file directly in a container field. This is required because if it's uncompressed to a .fmplugin file in the file system, it cannot be inserted into a container field as a file, from a Windows computer.

This has the potential to resolve an issue you mentioned here: http://www.goya.com.au/blog/updating-plugins-filemaker-pro-12

**Comment by nickorr** [comment]
Dan,

Following up on some old issues...

We've added gzip support now, and also ability to check for compression of containers, and ability to import and export files directly using the plugin.  So although this isn't resolved in a single function, it's now possible.

I'll close this unless you have any other related thoughts.

Cheers,
Nick
