### ISSUE TITLE
BE_JSONPath returning only ?

### ISSUE THREAD

**Issue by heathersswarner** [GoyaPtyLtd/BaseElements-Plugin#74]
Mac version 2.3.0, passing well-formed JSON and a wide range of valid paths, no result except "?" is returned. Are you using an alternate path syntax? It seems to use a subset of xpath formatting. 

// this is the json
{
	"store":{
		"book":[
			{
				"category":"reference",
				"author":"Nigel Rees",
				"title":"Sayings of the Century",
				"price":8.95
			},
			{
				"category":"fiction",
				"author":"Evelyn Waugh",
				"title":"Sword of Honour",
				"price":12.99
			},
			{
				"category":"fiction",
				"author":"J. R. R. Tolkien",
				"title":"The Lord of the Rings",
				"isbn":"0-395-19395-8",
				"price":22.99
			}
		],
		"bicycle":{
			"color":"red",
			"price":19.95
		}
	}
}

// this is the path
$..*

The only way I'm able to filter using the json path is in specifying the array value:
$.store.book[1]

the double-dot to return all values in the set doesn't work:
// this should return all book nodes; it doesn't
$..book

the complete path to all named values doesn't work:
// this should return a return carriage delimited list of all book titles; it doesn't
$.store.book.title

Any idea when (and if) the full path will be accessible?

**Comment by ernestkoe** [comment]
Hey Nick et al,
The plugin is brilliant; it's been part of our toolkit for a while but we've really just started to push it hard with our own REST services. Bummer about the JSON path thing though. Ran into this the other day, how difficult would it be to support the full path spec?

**Comment by nickorr** [comment]
Ernest,

Are you just after wildcard support?

Cheers,
Nick

**Comment by ernestkoe** [comment]
wildcard and [ ] support

On Thu, Feb 12, 2015 at 6:25 PM, Nicholas Orr <notifications@github.com>
wrote:

> Ernest,
>
> Are you just after wildcard support?
>
> Cheers,
> Nick
>
> > On 13 Feb 2015, at 9:28 am, Ernest Kkoe <notifications@github.com>
> wrote:
> >
> > Hey Nick et al,
> > The plugin is brilliant; it's been part of our toolkit for a while but
> we've really just started to push it hard with our own REST services.
> Bummer about the JSON path thing though. Ran into this the other day, how
> difficult would it be to support the full path spec?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/nickorr/BaseElements-Plugin/issues/74#issuecomment-74167154
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickorr/BaseElements-Plugin/issues/74#issuecomment-74175750>
> .
>



-- 
Ernest Y. Koe
President
The Proof Group LLC
http://twitter.com/ernestkoe

**Comment by laynebay** [comment]
I second the added support.  Nick, this plugin is amazing. the JSON functionality allows us to do so much.  It is a bit painful not to be able to wildcard, etc.  Thanks as always.

**Comment by nickorr** [comment]
Ernest, [ ] is supported, see the examples here : https://github.com/rogerz/jansson/wiki/Json-Path <https://github.com/rogerz/jansson/wiki/Json-Path>

laynebay, I've added it to the feature request section of the help site.  https://baseelementsplugin.zendesk.com/hc/en-us/articles/204109798 <https://baseelementsplugin.zendesk.com/hc/en-us/articles/204109798>

It's not in the library we're using, so we'd either need to work on that library and add support for it, or to find an alternative library to use.  I'm open to either solution.

Also please consider sponsoring, to help with the costs of development, and to push this up the todo list : http://www.goya.com.au/baseelements/plugin/sponsors

Thanks,
Nick

**Comment by dansmith65** [comment]
Has anybody looked into using the new javascript functions in the plugin and a jsonPath javascript library?

**Comment by nickorr** [comment]
Dan,

Not sure.  One of the options we'd considered with the js stuff was how to load external libraries.  It's not done yet, but is on the todo.

Cheers,
Nick

**Comment by laynebay** [comment]
Nick, 

Well, I considered sponsoring, and then I did so :-) The plugin helped us pull off something pretty big for a project. JSON is great, but the REST service can take JSON or XML and with BE_XPath, we can parse a bit easier for the more substantial results. love the ability to count(). and the BE_XPathAll goes a long way.

Cheers,
Michael

**Comment by ernestkoe** [comment]
Hey Nick,
Yeah, we'd be happy to sponsor. You guys are doing great work. [ ] works,
but * will be terrific. Currently, I am using SmartPill (PHP) to deal with
stuff that isn't supported by the JSON functions in the BE plugin.

Best

On Fri, Feb 20, 2015 at 10:26 PM, laynebay <notifications@github.com> wrote:

> Nick,
>
> Well, I considered sponsoring, and then I did so :-) The plugin helped us
> pull off something pretty big for a project. JSON is great, but the REST
> service can take JSON or XML and with BE_XPath, we can parse a bit easier
> for the more substantial results. love the ability to count(). and the
> BE_XPathAll goes a long way.
>
> Cheers,
> Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickorr/BaseElements-Plugin/issues/74#issuecomment-75353449>
> .
>



-- 
Ernest Y. Koe
President
The Proof Group LLC
http://twitter.com/ernestkoe

**Comment by laynebay** [comment]
Ernest, was going to DM you on Twitter, but couldn't.  I'm @9degrees.  Anyway - so getting off this thread for this is good, but my question is what version of FM are you using with SmartPill? After FM12, things broke (mostly around SQL). Thanks. Hope you're well. Nick, sorry for the use of this comment...

**Comment by nickorr** [comment]
Michael,

Thanks for the sponsorship, it’s much appreciated.  

I’ll see what we can do here, we’ve got a couple of big things just finishing up ( SMTP and javascript ), and also some things left to do ( libjpeg ) and lots of bug testing.

In my priority list, I want to look at a HTML to PDF engine so we can do server side reports, but also finish the javascript library loading aspects.  Also I want to look at server side functions for controlling FMS ( list files, load/unload, run schedule etc ).  And … we’ve been asked to build an Excel plugin based on this http://www.libxl.com <http://www.libxl.com/> which is a closed source product, so it would be have to be separate from the BE one, and a paid plugin.  So that will also keep us busy for a few months.

At this point, I don’t know when we’ll get to this, especially since it’s not just a case of updating the base library.  The definite short term fix would be to look at using the js functions and putting together a library of code examples ( custom functions ?? ) to do specific tasks.  I would imagine js can do this simply enough, but it’s not my area of expertise.  Perhaps if it requires an external library I can look at pushing that up the list.

Cheers,
Nick
