### ISSUE TITLE
Execute Javascript

### ISSUE THREAD

**Issue by toddgeist** [GoyaPtyLtd/BaseElements-Plugin#76]
http://duktape.org

The above is an embedable JavaScript engine for c programs. I would dearly love to see something like this make into the plugin

Ideally It could be like Scriptmaster but with JavaScript not groovy.

What do you think?

Todd

**Comment by toddgeist** [comment]
Hey Nick,

Great seeing you last week.  Things are sure getting interesting :-)

Where you planning on doing anything more with fmsadmin functions?  I am
going to build something for Barry ( the guy at the meeting last week ) and
was thinking of making it a product.  What are your plans?

Thanks

Todd
-- 
--
Todd Geist

**Comment by petrowsky** [comment]
Speaking of interesting... I'm sure you're familiar with this Todd.
http://browserify.org

;)

**Comment by toddgeist** [comment]
Oh darn that was supposed to go to nick directly.. :-(  deleted it.

**Comment by nickorr** [comment]
Todd,

Yep, things are looking bright.  I hope we contributed in a meaningful way to what they're trying to do.  At least the discussion around data in POST in curl, and import changes will be good small additions.  If they do the whole XML DDR move thing, that will be huge...

For the fmsadmin, I've already got some test functions done in the plugin.  My idea is to build a server side file that you can control remotely to start updates etc.  I hadn't yet decided whether it's a complete admin tool replacement, or something purely remote that has triggers to be called from other places or both.  I had envisaged something that RefreshFM could talk to to get files ready for updates.

What are your thoughts here?  I'm not sure it's a product by itself, I know lots of people have the same idea, so there'll be lots of competition, especially when FMI release their own API.

I think there's a larger opportunity to do a more advanced client/server management tool, so something that the Barrys of the world would utilise to track versioning across multiple servers etc.  The issue there is being able to remotely access all of the clients servers.  With some of the other plans I had, I was going to write something myself to do these sort of updates to other servers.

Did you want to collaborate on something here?

Cheers,
Nick

**Comment by shin9ball** [comment]
No prob!
Seems very interesting to me, too;-)

2016/03/10 18:58$B!"(BTodd Geist <notifications@github.com> $B$N%a%C%;!<%8(B:
