### ISSUE TITLE
Using BE_HTTP_POST to submit a request to a cURL API

### ISSUE THREAD

**Issue by docuwrxmskinner** [GoyaPtyLtd/BaseElements-Plugin#77]
I'm attempting to integrate [this API](https://www.easypost.com/docs/api) with my company's FileMaker solution and have run into a bit of trouble. I am using the cURL API and was planning to just use BE_HTTP_POST to submit the POST requests.

Typically this wouldn't be difficult, as the -d flag in cURL can be achieved rather simply using BE, but this API expects an authorization using the -u flag to submit an API key. Is this possible using the Base Elements plugin? I'm unsure how the syntax translates.

Any help is much appreciated. Thanks!

**Comment by sffmp** [comment]
Hello, our vendor has switched their invoicing from XLS to PDF.  We found an affordable way to convert PDF into JSON, then into our FmPro database [here](http://pdfextractoronline.com/tabex-pdf-api/#get-api) and was attempting to use the BE_HTTP_PUT function but am having trouble. I did receive the key! Could you help with this please?

**Comment by nickorr** [comment]
The GitHub issues list is for questions about compiling or coding within the plugin.  If you need help to implement the plugin, please check out the support options here :

https://baseelementsplugin.zendesk.com/hc/en-us/articles/115001543347-What-is-plugin-sponsorship-

Thanks.
