### ISSUE TITLE
BE_JSON_Encode does handle decimals that are between 0 and 1

### ISSUE THREAD

**Issue by toddgeist** [GoyaPtyLtd/BaseElements-Plugin#82]
[BE_JSON_Encode](https://github.com/nickorr/BaseElements-Plugin/wiki/Functions#be_json_encode--key--value--type--)  doesn't handle decimals without leading integers correctly

`BE_JSON_Encode ( "test" ; 0.0124  ) = "test":0`

it should be  

`BE_JSON_Encode ( "test" ; 0.0124  ) = "test": .0124`

**Comment by nickorr** [comment]
Todd,

From Mark :

> Thanks to Todd for the clear and to the point bug report.
> 
> It’s a bug in in FMs number to text coercion, it strips leading 0s.
> 
> The test case below now returns
> 
> 	0.0124
> 
> (as does BE_JSON_Encode ( "test" ; .0124 ).
> 
> It’ll be in the next build.

Cheers,
Nick

**Comment by toddgeist** [comment]
Great!

Todd

On Tue, Jan 13, 2015 at 9:13 PM, Nicholas Orr <notifications@github.com>
wrote:

> Todd,
>
> From Mark :
>
> > Thanks to Todd for the clear and to the point bug report.
> >
> > It’s a bug in in FMs number to text coercion, it strips leading 0s.
> >
> > The test case below now returns
> >
> > 0.0124
> >
> > (as does BE_JSON_Encode ( "test" ; .0124 ).
> >
> > It’ll be in the next build.
>
> Cheers,
> Nick
>
>
> > On 10 Jan 2015, at 12:01 pm, Todd Geist <notifications@github.com>
> wrote:
> >
> > BE_JSON_Encode <
> https://github.com/nickorr/BaseElements-Plugin/wiki/Functions#be_json_encode--key--value--type-->
> doesn't handle decimals without leading integers correctly
> >
> > BE_JSON_Encode ( "test" ; 0.0124 ) = "test":0
> >
> > it should be
> >
> > BE_JSON_Encode ( "test" ; 0.0124 ) = "test": .0124
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/nickorr/BaseElements-Plugin/issues/82>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickorr/BaseElements-Plugin/issues/82#issuecomment-69870199>
> .
>



-- 
Todd Geist


(800) 935-6068
