### ISSUE TITLE
BE_HTTP_POST SSL curl error 35

### ISSUE THREAD

**Issue by tohvanah** [GoyaPtyLtd/BaseElements-Plugin#88]
I'm getting a curl error 35 when trying to POST anything to https://www.thepassionatepen.org . The error is thrown very quickly, increasing the curl timeout has no effect. 

Is there any way to see curl's error buffer? Any suggestions? Thanks.

**Comment by nickorr** [comment]
Thanks for your email.

I'm sorry, but technical support for the plugin is available for sponsors only : http://www.goya.com.au/baseelements/plugin/sponsors  We receive a lot of requests for support via our email and our contact pages, but we're unable to dedicate the time to answer them all.  We get multiple plugin related requests per day, and responding to them is something we either would want to do properly or not at all, and at present we don't have the time to do it properly, and still be able to help our clients, and work on our other products.

We've created the sponsorship option to give people a way to help with the development and ongoing costs of the plugin, and to also get support questions answered.

If you've got general questions you need to ask, perhaps consider something like the FileMaker Technet forums.

Thanks for your understanding.
Goya Staff


tohvanah, this is a curl error, do a google search for "curl error 35 POST", that it's not a supported SSL type.  Make sure you've got the latest plugin.
