### ISSUE TITLE
PHP version of BE_Decrypt_AES

### ISSUE THREAD

**Issue by msloper** [GoyaPtyLtd/BaseElements-Plugin#89]
I am trying to make a function in PHP which will decrypt a string encrypted with BE_Encrypt_AES. 

 function decryptOpenssl( $key, $textToDecrypt ){ 		
	 	$encryptionMethod = 'AES-256-CFB'; 
		$raw = false;  // $raw If TRUE return base64 encoded string
		$iv =openssl_random_pseudo_bytes(openssl_cipher_iv_length($encryptionMethod));    return(openssl_decrypt($textToDecrypt, $encryptionMethod, $key, $raw, $iv));
  }

Has anyone tried to do this? My C skills are lacking and i don't think i am generating $iv the same as the plugin. 

Michael Sloper

**Comment by nickorr** [comment]
msloper,

Without replicating the code in C, I'm not sure it's possible.  I've asked about this before and the best answer is that the encrypt/decrypt should be done only inside the plugin.

We could certainly work on something that matches it outside the plugin, like PHP, but it's not on our todo list at the moment.

Cheers,
Nick
