### ISSUE TITLE
HTTP functions not handling decoding properly?

### ISSUE THREAD

**Issue by ernestkoe** [GoyaPtyLtd/BaseElements-Plugin#94]
Have you guys seen an issue where JSON data comes down looking like "C\u00e9line" where it is supposed to be "é"?

I am having some trouble handling these characters from my webservice which should be spitting out UTF-8. Not sure which end is the problem.

**Comment by dansmith65** [comment]
"C\u00e9line" is a valid json string. `\u` means the next 4 characters contain a unicode code point in hexadecimal. https://github.com/nickorr/BaseElements-Plugin/wiki/Functions#be_jsonpath--json--path- should be able to convert that to "Céline".

**Comment by ernestkoe** [comment]
The thing is, in everything else, I am seeing "é" and not that "\u00e9" unicode code point.

**Comment by ernestkoe** [comment]
so I just looked at your fm modular fm-json module--looks like you ran into this a while back and had to convert json with escaped unicode codepoints with a recursive script!

**Comment by dansmith65** [comment]
Correct; only control characters _have_ to be encoded as unicode codepoints in json, but any character _can_ be encoded as codepoints. I'm guessing the web service is generating json with non-standard characters converted to codepoints.
