### ISSUE TITLE
BE_SelectFile, BE_SelectFolder and BE_SaveFileDialog don't include volume name in returned path. Filemaker expects it for output though.

### ISSUE THREAD

**Issue by michaelfeihstel** [GoyaPtyLtd/BaseElements-Plugin#97]
I'd like to use BE_SaveFileDialog to let the user select the output path for a file that is going to be exported several script steps later. In order to do this I save the return value of BE_SaveFileDialog in a $path variable, which I later use in FileMaker's own export options. 

Whihle BE's return value seems to be a valid path in my opinion, FileMaker explicitely needs the root drive of the path in order to export the file to it. 

Example: Let's say I want to save the file example.csv in /Users/johndoe/Documents

BE_SaveFileDialog would give me the return value "/Users/johndoe/Documents/example.csv" which is fine. FileMaker however will only successfully export the file if the path includes the volume like "Macintosh HD/Users/johndoe/Documents/example.csv" - otherwise the export will fail. FileMaker's own Get ( DocumentsPath ) function contains the volume too.

Of course, I could prepend the volume name, but since this script will be used on different clients there's no way to know the volume name in advance. It may be possible to get the volume name by using one of FileMaker's Get functions and just keep the string before the first "/". However it makes the BE_SaveFileDialog and similar functions needlessly complicated and a lot less useful.

Am I missing something very obvious here?

**Comment by nilswald** [comment]
I think simple tasks that can easily be done by custom functions should not be integrated into plugins.

Nils

**Comment by EncryptedFile** [comment]
Concatenate.
Without seeing your script you need to have it look something like this:

"Macintosh HD" & $path variable

If you can post some, or all of your script in question I, and others like myself could take a look at it, and see if we could help you clear your current hurdle.

Keep in mind however that I am not some kind of FileMaker Yoda, but I have roughly a years worth of coding experience.

//Personal Note I registered for an account here just to post this, and hopefully more helpful postings in the not too distant future.

**Comment by nickorr** [comment]
There's an old, but still relevant post here : https://www.goya.com.au/blog/guide-filemaker-import-paths

The CF could be adjusted just by removing the code that checks for the FileVault volume, as that's only a Mac OS 10.6 issue.

Cheers,
Nick
