### ISSUE TITLE
BE_JSON_ENCODE - can't get Boolean out of this

### ISSUE THREAD

**Issue by stevenadeau** [GoyaPtyLtd/BaseElements-Plugin#99]
I've tried many many things, but I can't get a true Boolean out of this function.

I'm trying to get something that'll fit  { "test":true }

Here are some examples of what I've tried:

BE_JSON_Encode ( "test" ; "true" ; "Boolean" )
BE_JSON_Encode ( "test" ; true ; "Boolean" )
BE_JSON_Encode ( "test" ; true )
BE_JSON_Encode ( "test" ; GetAsBoolean(1) ; "Boolean" )
BE_JSON_Encode ( "test" ; GetAsBoolean(1) )
BE_JSON_Encode ( "test" ; GetAsBoolean(true) )

I checked in the file "BEJSON.cpp", and at line 106 it gets the native type and there's the if/else if for each types or so.

I managed to bypass this by using BE_JSON_ENCODE ( "test" ) & "true"

Am I doing something wrong or is the Bool type never caught by "value.GetNativeType()" ?

Also, the documentation says that we can send the type as the 3rd parameter. When I checked the code, this doesn't seem to be true appart from the "null" type.

**Comment by dansmith65** [comment]
I think this is a limitation with FileMaker itself; it doesn't really understand the concept of Booleans. What I mean by this is if you send the constant `True` or `GetasBoolean(1)` to any function, what the function actually receives is the number 1.

> I managed to bypass this by using `BE_JSON_ENCODE ( "test" ) & "true"`

I think that's how you'll have to do it.

I solved this issue in my set of json functions by introducing my own set of named constants, so the text value of "json:true" is encoded as as Boolean true in the json: https://github.com/dansmith65/FileMaker-JSON-Functions/blob/master/Functions/z_jsonEncodeSupport.fmfn#L52

**Comment by stevenadeau** [comment]
It definitely is a Filemaker problem, since it doesn't know what a boolean is, or it translates it to an integer. Either way, thanks for pointing out to your custom function, I'll give it a try.

Cheers !
